/**
 * Shared auto-code allocator for the bulk-import pipeline.
 *
 * Groups rows that need an item code, fetches the next sequence per category
 * via `allocateItemCodes`, and assigns codes back to each row in place.
 *
 * Used by both catalog and inventory bulk importers — keeps the standard
 * `INV-{CAT}-{NNN}` (GS1 / ISO 8000-110) consistent across flows.
 */
import { allocateItemCodes, type ItemCodeScope } from '@/utils/itemCodeGenerator';

interface CategoryLike {
  id: string;
  name: string;
  code?: string | null;
}

export interface AllocatableRow {
  category_id?: string;
  company_id?: string;
  item_code?: string;
  errors: string[];
  /** Marker set by the parser when item_code was blank in the CSV. */
  autoGenerateCode?: boolean;
  /** Inventory parser uses this name; supported as an alias. */
  autoGenerated?: boolean;
}

export interface AllocateOptions {
  scope: ItemCodeScope;
  /** Fallback company id used when the row didn't specify one (inventory only). */
  defaultCompanyId?: string | null;
}

/**
 * Mutates `rows` in place: rows with `autoGenerateCode === true` (and a
 * resolvable category) receive sequential `INV-{CAT}-{NNN}` codes.
 *
 * Rows with unresolvable categories receive an error and are left without a code.
 *
 * Returns true when all auto-generation attempts succeeded; false when at least
 * one group failed (caller can decide whether to abort).
 */
export async function allocateAutoCodes(
  rows: AllocatableRow[],
  categories: CategoryLike[],
  options: AllocateOptions,
): Promise<boolean> {
  const targets = rows.filter(
    (r) => (r.autoGenerateCode || r.autoGenerated) && !r.item_code && r.category_id && r.errors.length === 0,
  );

  if (targets.length === 0) return true;

  // Group by (category, company) — company only matters for inventory scope.
  const groups = new Map<string, AllocatableRow[]>();
  for (const row of targets) {
    const companyKey =
      options.scope === 'inventory' ? row.company_id || options.defaultCompanyId || '' : '';
    const key = `${row.category_id}::${companyKey}`;
    if (!groups.has(key)) groups.set(key, []);
    groups.get(key)!.push(row);
  }

  let allSucceeded = true;

  for (const [key, groupRows] of groups.entries()) {
    const [categoryId, companyId] = key.split('::');
    const category = categories.find((c) => c.id === categoryId);
    const catCode = category?.code?.trim();

    if (!catCode) {
      allSucceeded = false;
      groupRows.forEach((r) =>
        r.errors.push(
          `Category "${category?.name || 'unknown'}" has no 3-letter code configured — cannot auto-generate item code`,
        ),
      );
      continue;
    }

    try {
      const codes = await allocateItemCodes({
        categoryCode: catCode,
        count: groupRows.length,
        scope: options.scope,
        companyId: options.scope === 'inventory' ? companyId || null : null,
      });
      groupRows.forEach((row, idx) => {
        row.item_code = codes[idx];
      });
    } catch (err: any) {
      allSucceeded = false;
      groupRows.forEach((r) =>
        r.errors.push(`Auto-code allocation failed: ${err?.message || 'Unknown error'}`),
      );
    }
  }

  return allSucceeded;
}
