import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import { useCompany } from "@/contexts/CompanyContext";
import type { DailySiteReport, CreateDailySiteReportData, UpdateDailySiteReportData, SiteReportActivity } from "@/types/construction";
import { format } from "date-fns";

type DailySiteReportWithProject = Omit<DailySiteReport, 'project'> & {
  project?: { id: string; project_name: string; project_code: string } | null;
  activities?: SiteReportActivity[];
};

export function useDailySiteReports(projectId?: string) {
  const { selectedCompany } = useCompany();

  return useQuery({
    queryKey: ["daily-site-reports", selectedCompany?.id, projectId],
    queryFn: async () => {
      let query = supabase
        .from("daily_site_reports")
        .select(`
          *,
          project:construction_projects(id, project_name, project_code),
          activities:site_report_activities(*)
        `)
        .order("report_date", { ascending: false });

      if (selectedCompany?.id) {
        query = query.eq("company_id", selectedCompany.id);
      }

      if (projectId) {
        query = query.eq("project_id", projectId);
      }

      const { data, error } = await query;

      if (error) throw error;
      return data as DailySiteReportWithProject[];
    },
    enabled: !!selectedCompany?.id,
  });
}

export function useCreateDailySiteReport() {
  const queryClient = useQueryClient();
  const { toast } = useToast();
  const { selectedCompany } = useCompany();

  return useMutation({
    mutationFn: async (data: CreateDailySiteReportData) => {
      const { data: user } = await supabase.auth.getUser();
      
      const insertData = {
        ...data,
        company_id: selectedCompany?.id,
        submitted_by: user.user?.id,
      };
      
      const { data: result, error } = await supabase
        .from("daily_site_reports")
        .insert(insertData as any)
        .select()
        .single();

      if (error) throw error;
      return result;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["daily-site-reports"] });
      toast({ title: "Daily site report created successfully" });
    },
    onError: (error: Error) => {
      toast({ title: "Error creating report", description: error.message, variant: "destructive" });
    },
  });
}

export function useUpdateDailySiteReport() {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async ({ id, ...data }: UpdateDailySiteReportData & { id: string }) => {
      const { data: result, error } = await supabase
        .from("daily_site_reports")
        .update(data)
        .eq("id", id)
        .select()
        .single();

      if (error) throw error;
      return result;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["daily-site-reports"] });
      toast({ title: "Report updated successfully" });
    },
    onError: (error: Error) => {
      toast({ title: "Error updating report", description: error.message, variant: "destructive" });
    },
  });
}

export function useDeleteDailySiteReport() {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase
        .from("daily_site_reports")
        .delete()
        .eq("id", id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["daily-site-reports"] });
      toast({ title: "Report deleted successfully" });
    },
    onError: (error: Error) => {
      toast({ title: "Error deleting report", description: error.message, variant: "destructive" });
    },
  });
}

// Site Report Activities
export function useCreateReportActivity() {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async (data: Omit<SiteReportActivity, "id" | "created_at">) => {
      const { data: result, error } = await supabase
        .from("site_report_activities")
        .insert(data)
        .select()
        .single();

      if (error) throw error;
      return result;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["daily-site-reports"] });
      toast({ title: "Activity added successfully" });
    },
    onError: (error: Error) => {
      toast({ title: "Error adding activity", description: error.message, variant: "destructive" });
    },
  });
}

// Auto-generate daily site reports for projects with material activity
export function useAutoGenerateDailySiteReports() {
  const queryClient = useQueryClient();
  const { toast } = useToast();
  const { selectedCompany } = useCompany();

  return useMutation({
    mutationFn: async (targetDate?: string) => {
      const dateToUse = targetDate || format(new Date(), 'yyyy-MM-dd');
      const { data: user } = await supabase.auth.getUser();

      if (!selectedCompany?.id) {
        throw new Error("No company selected");
      }

      // Get all active construction projects for this company
      const { data: projects, error: projectsError } = await supabase
        .from("construction_projects")
        .select("id, project_name, project_code")
        .eq("company_id", selectedCompany.id)
        .in("status", ["active", "in_progress", "planning"]);

      if (projectsError) throw projectsError;
      if (!projects || projects.length === 0) {
        return { generated: 0, skipped: 0, message: "No active projects found" };
      }

      // Check which projects already have reports for the target date
      const { data: existingReports, error: existingError } = await supabase
        .from("daily_site_reports")
        .select("project_id")
        .eq("company_id", selectedCompany.id)
        .eq("report_date", dateToUse);

      if (existingError) throw existingError;

      const existingProjectIds = new Set((existingReports || []).map(r => r.project_id));

      // Filter out projects that already have a report
      const projectsToGenerate = projects.filter(p => !existingProjectIds.has(p.id));

      if (projectsToGenerate.length === 0) {
        return { 
          generated: 0, 
          skipped: projects.length, 
          message: "All projects already have reports for this date" 
        };
      }

      // For each project, check if there's material activity and generate a report
      const generatedReports: string[] = [];
      const skippedNoActivity: string[] = [];

      for (const project of projectsToGenerate) {
        // Get floor drawings for this project
        const { data: floors } = await supabase
          .from("project_floor_drawings")
          .select("id, drawing_name")
          .eq("project_id", project.id);

        if (!floors || floors.length === 0) {
          skippedNoActivity.push(project.id);
          continue;
        }

        const floorIds = floors.map(f => f.id);

        // Get rooms for these floors
        const { data: rooms } = await supabase
          .from("floor_drawing_rooms")
          .select("id")
          .in("floor_drawing_id", floorIds);

        if (!rooms || rooms.length === 0) {
          skippedNoActivity.push(project.id);
          continue;
        }

        const roomIds = rooms.map(r => r.id);

        // Check for material transactions on the target date
        const { data: transactions } = await supabase
          .from("floor_room_material_transactions")
          .select("id, transaction_type, quantity, total_value")
          .in("room_id", roomIds)
          .gte("created_at", `${dateToUse}T00:00:00`)
          .lt("created_at", `${dateToUse}T23:59:59.999`);

        if (!transactions || transactions.length === 0) {
          skippedNoActivity.push(project.id);
          continue;
        }

        // Calculate material summary
        let issuedCount = 0;
        let returnedCount = 0;
        let issuedValue = 0;
        let returnedValue = 0;

        transactions.forEach(t => {
          if (t.transaction_type === 'issue') {
            issuedCount += t.quantity || 0;
            issuedValue += t.total_value || 0;
          } else if (t.transaction_type === 'return') {
            returnedCount += t.quantity || 0;
            returnedValue += t.total_value || 0;
          }
        });

        // Generate report number
        const reportDate = new Date(dateToUse);
        const reportNumber = `DSR-${project.project_code}-${format(reportDate, 'yyyyMMdd')}`;

        // Build work summary from material data
        const workSummary = `Auto-generated report: ${issuedCount} materials issued (₦${issuedValue.toLocaleString()}), ${returnedCount} materials returned (₦${returnedValue.toLocaleString()}) across ${floors.length} floor(s).`;

        // Create the daily site report
        const { error: insertError } = await supabase
          .from("daily_site_reports")
          .insert({
            report_number: reportNumber,
            project_id: project.id,
            report_date: dateToUse,
            status: "draft",
            work_summary: workSummary,
            materials_received: `Issued: ${issuedCount} items, Returned: ${returnedCount} items`,
            company_id: selectedCompany.id,
            submitted_by: user.user?.id,
          });

        if (insertError) {
          console.error(`Failed to generate report for ${project.project_code}:`, insertError);
          continue;
        }

        generatedReports.push(project.id);
      }

      return {
        generated: generatedReports.length,
        skipped: skippedNoActivity.length + existingProjectIds.size,
        message: `Generated ${generatedReports.length} report(s)`,
      };
    },
    onSuccess: (result) => {
      queryClient.invalidateQueries({ queryKey: ["daily-site-reports"] });
      if (result.generated > 0) {
        toast({ 
          title: "Reports Generated", 
          description: `${result.generated} report(s) created, ${result.skipped} skipped` 
        });
      } else {
        toast({ 
          title: "No Reports Generated", 
          description: result.message,
          variant: "default"
        });
      }
    },
    onError: (error: Error) => {
      toast({ title: "Error generating reports", description: error.message, variant: "destructive" });
    },
  });
}
