import { useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { CreateProjectData, UpdateProjectData } from "@/types/construction";
import { useCompany } from "@/contexts/CompanyContext";
import { toast } from "sonner";

export function useCreateProject() {
  const queryClient = useQueryClient();
  const { selectedCompany } = useCompany();

  return useMutation({
    mutationFn: async (data: CreateProjectData) => {
      const { data: user } = await supabase.auth.getUser();
      
      const insertData = {
        project_code: '', // Will be auto-generated by trigger
        project_name: data.project_name,
        description: data.description || null,
        client_name: data.client_name || null,
        client_contact: data.client_contact || null,
        project_type: data.project_type || null,
        status: data.status || 'planning',
        start_date: data.start_date || null,
        target_end_date: data.target_end_date || null,
        estimated_budget: data.estimated_budget || null,
        project_manager_id: data.project_manager_id || null,
        address: data.address || null,
        city: data.city || null,
        state: data.state || null,
        country: data.country || null,
        contract_number: data.contract_number || null,
        contract_value: data.contract_value || null,
        notes: data.notes || null,
        company_id: selectedCompany?.id || null,
        created_by: user.user?.id || null,
      };

      const { data: result, error } = await supabase
        .from("construction_projects")
        .insert(insertData)
        .select()
        .single();

      if (error) throw error;
      return result;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["construction-projects"] });
      toast.success("Project created successfully");
    },
    onError: (error: Error) => {
      toast.error(`Failed to create project: ${error.message}`);
    },
  });
}

export function useUpdateProject() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ id, ...data }: UpdateProjectData) => {
      const { data: result, error } = await supabase
        .from("construction_projects")
        .update(data)
        .eq("id", id)
        .select()
        .single();

      if (error) throw error;
      return result;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["construction-projects"] });
      toast.success("Project updated successfully");
    },
    onError: (error: Error) => {
      toast.error(`Failed to update project: ${error.message}`);
    },
  });
}

export function useDeleteProject() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase
        .from("construction_projects")
        .delete()
        .eq("id", id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["construction-projects"] });
      toast.success("Project deleted successfully");
    },
    onError: (error: Error) => {
      toast.error(`Failed to delete project: ${error.message}`);
    },
  });
}
