import { useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { CreateProjectData, UpdateProjectData } from "@/types/construction";
import { useCompany } from "@/contexts/CompanyContext";
import { toast } from "sonner";

// Helper to convert empty strings to null for date/numeric fields
function cleanForDb(data: Record<string, any>) {
  const cleaned = { ...data };
  const dateFields = ['start_date', 'target_end_date', 'actual_end_date'];
  const numericFields = ['estimated_budget', 'contract_value', 'actual_cost', 'completion_percentage'];
  
  for (const field of dateFields) {
    if (field in cleaned && (cleaned[field] === '' || cleaned[field] === undefined)) {
      cleaned[field] = null;
    }
  }
  for (const field of numericFields) {
    if (field in cleaned && (cleaned[field] === '' || cleaned[field] === undefined || cleaned[field] === 0)) {
      cleaned[field] = null;
    }
  }
  // Remove fields not in DB table
  delete cleaned.company_ids;
  return cleaned;
}

async function syncProjectCompanies(projectId: string, companyIds: string[]) {
  // Delete existing mappings
  await supabase
    .from("construction_project_companies")
    .delete()
    .eq("project_id", projectId);

  // Insert new mappings
  if (companyIds.length > 0) {
    const rows = companyIds.map((cid) => ({ project_id: projectId, company_id: cid }));
    const { error } = await supabase
      .from("construction_project_companies")
      .insert(rows);
    if (error) throw error;
  }
}

export function useCreateProject() {
  const queryClient = useQueryClient();
  const { selectedCompany } = useCompany();

  return useMutation({
    mutationFn: async (data: CreateProjectData) => {
      const { data: user } = await supabase.auth.getUser();
      const companyIds = data.company_ids || (selectedCompany?.id ? [selectedCompany.id] : []);

      const insertData = cleanForDb({
        project_code: '', // Will be auto-generated by trigger
        project_name: data.project_name,
        description: data.description || null,
        client_name: data.client_name || null,
        client_contact: data.client_contact || null,
        project_type: data.project_type || null,
        status: data.status || 'planning',
        start_date: data.start_date || null,
        target_end_date: data.target_end_date || null,
        estimated_budget: data.estimated_budget || null,
        project_manager_id: data.project_manager_id || null,
        address: data.address || null,
        city: data.city || null,
        state: data.state || null,
        country: data.country || null,
        contract_number: data.contract_number || null,
        contract_value: data.contract_value || null,
        notes: data.notes || null,
        location_id: data.location_id || null,
        company_id: companyIds[0] || selectedCompany?.id || null,
        created_by: user.user?.id || null,
      });

      const { data: result, error } = await supabase
        .from("construction_projects")
        .insert(insertData as any)
        .select()
        .single();

      if (error) throw error;

      // Sync multi-company junction
      await syncProjectCompanies(result.id, companyIds);

      return result;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["construction-projects"] });
      toast.success("Project created successfully");
    },
    onError: (error: Error) => {
      toast.error(`Failed to create project: ${error.message}`);
    },
  });
}

export function useUpdateProject() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ id, company_ids, ...data }: UpdateProjectData) => {
      const cleaned = cleanForDb(data);
      
      // Set primary company_id from first selected company
      if (company_ids && company_ids.length > 0) {
        cleaned.company_id = company_ids[0];
      }

      const { data: result, error } = await supabase
        .from("construction_projects")
        .update(cleaned as any)
        .eq("id", id)
        .select()
        .single();

      if (error) throw error;

      // Sync multi-company junction if provided
      if (company_ids) {
        await syncProjectCompanies(id, company_ids);
      }

      return result;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["construction-projects"] });
      toast.success("Project updated successfully");
    },
    onError: (error: Error) => {
      toast.error(`Failed to update project: ${error.message}`);
    },
  });
}

export function useDeleteProject() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase
        .from("construction_projects")
        .delete()
        .eq("id", id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["construction-projects"] });
      toast.success("Project deleted successfully");
    },
    onError: (error: Error) => {
      toast.error(`Failed to delete project: ${error.message}`);
    },
  });
}
