import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { BillOfMaterials, BomItem, CreateBomData, UpdateBomData } from '@/types/bom';
import { useToast } from '@/hooks/use-toast';

export function useBillOfMaterials(companyId?: string) {
  const { toast } = useToast();
  const queryClient = useQueryClient();

  const {
    data: boms = [],
    isLoading,
    error
  } = useQuery({
    queryKey: ['bill-of-materials', companyId],
    queryFn: async () => {
      let query = supabase
        .from('bill_of_materials')
        .select('*')
        .order('created_at', { ascending: false });

      if (companyId) {
        query = query.eq('company_id', companyId);
      }

      const { data, error } = await query;
      if (error) throw error;
      return data as BillOfMaterials[];
    }
  });

  const createBomMutation = useMutation({
    mutationFn: async (bomData: CreateBomData) => {
      const { items, ...bomDetails } = bomData;
      const user = await supabase.auth.getUser();

      // Create BOM - bom_number will be auto-generated by the database
      const { data: bomResult, error: bomError } = await supabase
        .from('bill_of_materials')
        .insert({
          ...bomDetails,
          created_by: user.data.user?.id,
          warehouse_item_id: bomDetails.warehouse_item_id || null
        } as any)
        .select()
        .single();

      if (bomError) throw bomError;

      // Create BOM items
      if (items.length > 0) {
        const bomItems = items.map(item => ({
          ...item,
          bom_id: bomResult.id,
          total_cost: item.unit_cost ? (item.consumption || 0) * item.unit_cost : undefined
        }));

        const { error: itemsError } = await supabase
          .from('bom_items')
          .insert(bomItems);

        if (itemsError) throw itemsError;
      }

      return bomResult as BillOfMaterials;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['bill-of-materials'] });
      toast({
        title: "Success",
        description: "Bill of Materials created successfully",
      });
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: error.message || "Failed to create BOM",
        variant: "destructive",
      });
    }
  });

  const updateBomMutation = useMutation({
    mutationFn: async ({ id, items, ...updateData }: UpdateBomData) => {
      // Update BOM details (excluding items)
      const { data: bomResult, error: bomError } = await supabase
        .from('bill_of_materials')
        .update(updateData as any)
        .eq('id', id)
        .select()
        .single();

      if (bomError) throw bomError;

      // If items are provided, update them
      if (items && items.length > 0) {
        // Delete existing items
        const { error: deleteError } = await supabase
          .from('bom_items')
          .delete()
          .eq('bom_id', id);

        if (deleteError) throw deleteError;

        // Insert new items
        const bomItems = items.map(item => ({
          ...item,
          bom_id: id,
          total_cost: item.unit_cost ? (item.consumption || 0) * item.unit_cost : undefined
        }));

        const { error: itemsError } = await supabase
          .from('bom_items')
          .insert(bomItems);

        if (itemsError) throw itemsError;
      }

      return bomResult as BillOfMaterials;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ['bill-of-materials'] });
      queryClient.invalidateQueries({ queryKey: ['bom-items', data.id] });
      toast({
        title: "Success",
        description: "BOM updated successfully",
      });
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: error.message || "Failed to update BOM",
        variant: "destructive",
      });
    }
  });

  const deleteBomMutation = useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase
        .from('bill_of_materials')
        .delete()
        .eq('id', id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['bill-of-materials'] });
      toast({
        title: "Success",
        description: "BOM deleted successfully",
      });
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: error.message || "Failed to delete BOM",
        variant: "destructive",
      });
    }
  });

  const duplicateBomMutation = useMutation({
    mutationFn: async (id: string) => {
      // Fetch original BOM
      const { data: originalBom, error: bomError } = await supabase
        .from('bill_of_materials')
        .select('*')
        .eq('id', id)
        .single();

      if (bomError) throw bomError;

      // Fetch BOM items
      const { data: originalItems, error: itemsError } = await supabase
        .from('bom_items')
        .select('*')
        .eq('bom_id', id);

      if (itemsError) throw itemsError;

      // Fetch linked finished goods
      const { data: linkedProducts, error: linkedError } = await supabase
        .from('bom_finished_goods')
        .select('finished_good_id')
        .eq('bom_id', id);

      if (linkedError) throw linkedError;

      const user = await supabase.auth.getUser();

      // Increment version
      const incrementVersion = (version: string): string => {
        const numericMatch = version.match(/^(\d+)\.(\d+)$/);
        if (numericMatch) {
          const [, major, minor] = numericMatch;
          return `${major}.${parseInt(minor) + 1}`;
        }
        const majorOnlyMatch = version.match(/^(\d+)$/);
        if (majorOnlyMatch) {
          return `${majorOnlyMatch[1]}.1`;
        }
        return `${version} (Copy)`;
      };

      // Create new BOM
      const { data: newBom, error: createError } = await supabase
        .from('bill_of_materials')
        .insert({
          product_name: `${originalBom.product_name} (Copy)`,
          product_master_id: originalBom.product_master_id,
          warehouse_item_id: originalBom.warehouse_item_id,
          style_no: originalBom.style_no,
          version: incrementVersion(originalBom.version),
          size: originalBom.size,
          description: originalBom.description,
          status: 'draft',
          company_id: originalBom.company_id,
          created_by: user.data.user?.id,
        } as any)
        .select()
        .single();

      if (createError) throw createError;

      // Duplicate BOM items
      if (originalItems && originalItems.length > 0) {
        const newItems = originalItems.map(item => ({
          bom_id: newBom.id,
          item_name: item.item_name,
          description: item.description,
          quantity: item.quantity,
          unit_of_measure: item.unit_of_measure,
          unit_cost: item.unit_cost,
          total_cost: item.total_cost,
          supplier_part_number: item.supplier_part_number,
          manufacturer_part_number: item.manufacturer_part_number,
          po_item_id: item.po_item_id,
          notes: item.notes,
          item_code: item.item_code,
          consumption: item.consumption,
          category: item.category,
          warehouse_item_id: item.warehouse_item_id,
        }));

        const { error: insertItemsError } = await supabase
          .from('bom_items')
          .insert(newItems);

        if (insertItemsError) throw insertItemsError;
      }

      // Do not copy linked finished goods on duplicate. We'll let users manage links in the edit screen.
      // This avoids DB trigger errors related to finished_good_id.
      // If needed later, implement a safe copy with proper validations.


      return newBom;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ['bill-of-materials'] });
      queryClient.invalidateQueries({ queryKey: ['bom-linked-products-counts'] });
      queryClient.invalidateQueries({ queryKey: ['bom-linked-products-details'] });
      toast({
        title: "Success",
        description: `BOM duplicated successfully as ${data.bom_number}`,
      });
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: error.message || "Failed to duplicate BOM",
        variant: "destructive",
      });
    }
  });

  return {
    boms,
    isLoading,
    error,
    createBom: createBomMutation.mutateAsync,
    updateBom: updateBomMutation.mutateAsync,
    deleteBom: deleteBomMutation.mutateAsync,
    duplicateBom: duplicateBomMutation.mutateAsync,
    isCreating: createBomMutation.isPending,
    isUpdating: updateBomMutation.isPending,
    isDeleting: deleteBomMutation.isPending,
    isDuplicating: duplicateBomMutation.isPending,
  };
}

export function useBomItems(bomId: string) {
  const { toast } = useToast();
  const queryClient = useQueryClient();

  const {
    data: items = [],
    isLoading,
    error
  } = useQuery({
    queryKey: ['bom-items', bomId],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('bom_items')
        .select('*')
        .eq('bom_id', bomId)
        .order('created_at', { ascending: true });

      if (error) throw error;
      return data as BomItem[];
    },
    enabled: !!bomId
  });

  return {
    items,
    isLoading,
    error,
  };
}