import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { BillOfMaterials, BomItem, CreateBomData, UpdateBomData } from '@/types/bom';
import { useToast } from '@/hooks/use-toast';

export function useBillOfMaterials(companyId?: string) {
  const { toast } = useToast();
  const queryClient = useQueryClient();

  const {
    data: boms = [],
    isLoading,
    error
  } = useQuery({
    queryKey: ['bill-of-materials', companyId],
    queryFn: async () => {
      let query = supabase
        .from('bill_of_materials')
        .select('*')
        .order('created_at', { ascending: false });

      if (companyId) {
        query = query.eq('company_id', companyId);
      }

      const { data, error } = await query;
      if (error) throw error;
      return data as BillOfMaterials[];
    }
  });

  const createBomMutation = useMutation({
    mutationFn: async (bomData: CreateBomData) => {
      const { items, ...bomDetails } = bomData;
      const user = await supabase.auth.getUser();

      // Create BOM - bom_number will be auto-generated by the database
      const { data: bomResult, error: bomError } = await supabase
        .from('bill_of_materials')
        .insert({
          ...bomDetails,
          created_by: user.data.user?.id,
          warehouse_item_id: bomDetails.warehouse_item_id || null
        } as any)
        .select()
        .single();

      if (bomError) throw bomError;

      // Create BOM items
      if (items.length > 0) {
        const bomItems = items.map(item => ({
          ...item,
          bom_id: bomResult.id,
          total_cost: item.unit_cost ? (item.consumption || 0) * item.unit_cost : undefined
        }));

        const { error: itemsError } = await supabase
          .from('bom_items')
          .insert(bomItems);

        if (itemsError) throw itemsError;
      }

      return bomResult as BillOfMaterials;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['bill-of-materials'] });
      toast({
        title: "Success",
        description: "Bill of Materials created successfully",
      });
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: error.message || "Failed to create BOM",
        variant: "destructive",
      });
    }
  });

  const updateBomMutation = useMutation({
    mutationFn: async ({ id, items, ...updateData }: UpdateBomData) => {
      // Update BOM details (excluding items)
      const { data: bomResult, error: bomError } = await supabase
        .from('bill_of_materials')
        .update(updateData as any)
        .eq('id', id)
        .select()
        .single();

      if (bomError) throw bomError;

      // If items are provided, update them
      if (items && items.length > 0) {
        // Delete existing items
        const { error: deleteError } = await supabase
          .from('bom_items')
          .delete()
          .eq('bom_id', id);

        if (deleteError) throw deleteError;

        // Insert new items
        const bomItems = items.map(item => ({
          ...item,
          bom_id: id,
          total_cost: item.unit_cost ? (item.consumption || 0) * item.unit_cost : undefined
        }));

        const { error: itemsError } = await supabase
          .from('bom_items')
          .insert(bomItems);

        if (itemsError) throw itemsError;
      }

      return bomResult as BillOfMaterials;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ['bill-of-materials'] });
      queryClient.invalidateQueries({ queryKey: ['bom-items', data.id] });
      toast({
        title: "Success",
        description: "BOM updated successfully",
      });
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: error.message || "Failed to update BOM",
        variant: "destructive",
      });
    }
  });

  const deleteBomMutation = useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase
        .from('bill_of_materials')
        .delete()
        .eq('id', id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['bill-of-materials'] });
      toast({
        title: "Success",
        description: "BOM deleted successfully",
      });
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: error.message || "Failed to delete BOM",
        variant: "destructive",
      });
    }
  });

  return {
    boms,
    isLoading,
    error,
    createBom: createBomMutation.mutateAsync,
    updateBom: updateBomMutation.mutateAsync,
    deleteBom: deleteBomMutation.mutateAsync,
    isCreating: createBomMutation.isPending,
    isUpdating: updateBomMutation.isPending,
    isDeleting: deleteBomMutation.isPending,
  };
}

export function useBomItems(bomId: string) {
  const { toast } = useToast();
  const queryClient = useQueryClient();

  const {
    data: items = [],
    isLoading,
    error
  } = useQuery({
    queryKey: ['bom-items', bomId],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('bom_items')
        .select('*')
        .eq('bom_id', bomId)
        .order('created_at', { ascending: true });

      if (error) throw error;
      return data as BomItem[];
    },
    enabled: !!bomId
  });

  return {
    items,
    isLoading,
    error,
  };
}