import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import type {
import { flattenCatalog } from '@/lib/flattenWarehouseItem';
  CycleCount,
  CycleCountItem,
  CycleCountSchedule,
  CreateCycleCountData,
  CreateCycleCountItemData,
  UpdateCycleCountItemData,
  CycleCountStatus,
} from "@/types/cycleCount";

// Fetch all cycle counts
export const useCycleCounts = (status?: CycleCountStatus) => {
  return useQuery({
    queryKey: ["cycle-counts", status],
    queryFn: async () => {
      let query = supabase
        .from("cycle_counts")
        .select("*")
        .order("created_at", { ascending: false });

      if (status) {
        query = query.eq("status", status);
      }

      const { data, error } = await query;
      if (error) throw error;
      return data as unknown as CycleCount[];
    },
  });
};

// Fetch single cycle count
export const useCycleCount = (countId: string | undefined) => {
  return useQuery({
    queryKey: ["cycle-count", countId],
    queryFn: async () => {
      if (!countId) return null;

      const { data, error } = await supabase
        .from("cycle_counts")
        .select("*")
        .eq("id", countId)
        .single();

      if (error) throw error;
      return data as unknown as CycleCount;
    },
    enabled: !!countId,
  });
};

// Fetch cycle count items
export const useCycleCountItems = (countId: string | undefined) => {
  return useQuery({
    queryKey: ["cycle-count-items", countId],
    queryFn: async () => {
      if (!countId) return [];

      const { data, error } = await supabase
        .from("cycle_count_items")
        .select(`
          *,
          warehouse_items(
            id,
            item_name,
            unit_of_measure,
            current_stock,
            unit_cost,
            catalog:warehouse_item_catalog!warehouse_items_catalog_item_id_fkey(item_code)
          ),
          warehouse_bins (
            id,
            bin_code,
            location_id
          )
        `)
        .eq("cycle_count_id", countId)
        .order("created_at", { ascending: true });

      if (error) throw error;
      return data as any[];
    },
    enabled: !!countId,
  });
};

// Fetch schedules
export const useCycleCountSchedules = () => {
  return useQuery({
    queryKey: ["cycle-count-schedules"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("cycle_count_schedules")
        .select("*")
        .order("created_at", { ascending: false });

      if (error) throw error;
      return data as unknown as CycleCountSchedule[];
    },
  });
};

// Create cycle count
export const useCreateCycleCount = () => {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async (data: CreateCycleCountData) => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error("User not authenticated");

      const { data: cycleCount, error } = await supabase
        .from("cycle_counts")
        .insert({
          ...data,
          count_number: '', // Auto-generated by trigger
          created_by: user.id,
        })
        .select()
        .single();

      if (error) throw error;
      return cycleCount as unknown as CycleCount;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["cycle-counts"] });
      toast({
        title: "Cycle Count Created",
        description: "Cycle count session created successfully.",
      });
    },
    onError: (error) => {
      console.error("Create cycle count error:", error);
      toast({
        title: "Error",
        description: "Failed to create cycle count.",
        variant: "destructive",
      });
    },
  });
};

// Add item to cycle count
export const useAddCycleCountItem = () => {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async (data: CreateCycleCountItemData) => {
      const { data: item, error } = await supabase
        .from("cycle_count_items")
        .insert(data)
        .select()
        .single();

      if (error) throw error;
      return item as unknown as CycleCountItem;
    },
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ["cycle-count-items", variables.cycle_count_id] });
      queryClient.invalidateQueries({ queryKey: ["cycle-count", variables.cycle_count_id] });
    },
  });
};

// Update cycle count item (record physical count)
export const useUpdateCycleCountItem = () => {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async ({ id, countId, data }: { 
      id: string; 
      countId: string;
      data: UpdateCycleCountItemData 
    }) => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error("User not authenticated");

      const { error } = await supabase
        .from("cycle_count_items")
        .update({
          ...data,
          counted_by: user.id,
          counted_at: new Date().toISOString(),
        })
        .eq("id", id);

      if (error) throw error;
    },
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ["cycle-count-items", variables.countId] });
      queryClient.invalidateQueries({ queryKey: ["cycle-count", variables.countId] });
      toast({
        title: "Count Recorded",
        description: "Physical count recorded successfully.",
      });
    },
    onError: (error) => {
      console.error("Update count item error:", error);
      toast({
        title: "Error",
        description: "Failed to record count.",
        variant: "destructive",
      });
    },
  });
};

// Start cycle count
export const useStartCycleCount = () => {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async (countId: string) => {
      const { error } = await supabase
        .from("cycle_counts")
        .update({
          status: 'in_progress',
          started_at: new Date().toISOString(),
        })
        .eq("id", countId);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["cycle-counts"] });
      toast({
        title: "Count Started",
        description: "Cycle count session has been started.",
      });
    },
  });
};

// Complete cycle count
export const useCompleteCycleCount = () => {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async (countId: string) => {
      const { error } = await supabase
        .from("cycle_counts")
        .update({
          status: 'completed',
          completed_at: new Date().toISOString(),
        })
        .eq("id", countId);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["cycle-counts"] });
      queryClient.invalidateQueries({ queryKey: ["warehouse-items"] });
      toast({
        title: "Count Completed",
        description: "Cycle count session has been completed.",
      });
    },
  });
};

// Post adjustments from cycle count
export const usePostCycleCountAdjustments = () => {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async ({ countId, itemIds }: { countId: string; itemIds: string[] }) => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error("User not authenticated");

      // Get items with variance
      const { data: items, error: itemsError } = await supabase
        .from("cycle_count_items")
        .select("*")
        .eq("cycle_count_id", countId)
        .in("id", itemIds);

      if (itemsError) throw itemsError;

      // Process each item with variance
      for (const item of items || []) {
        if (item.variance_quantity && item.variance_quantity !== 0) {
          // Get current stock
          const { data: warehouseItem } = await supabase
            .from("warehouse_items_full")
            .select("current_stock")
            .eq("id", item.warehouse_item_id)
            .single();

          const currentStock = warehouseItem?.current_stock || 0;

          // Create stock transaction
          const { data: transaction } = await supabase
            .from("stock_transactions")
            .insert({
              item_id: item.warehouse_item_id,
              transaction_type: 'adjustment',
              reference_type: 'manual',
              reference_id: countId,
              quantity_change: item.variance_quantity,
              quantity_before: currentStock,
              quantity_after: currentStock + item.variance_quantity,
              notes: `Cycle Count Adjustment - ${item.variance_reason || 'Variance detected'}`,
              created_by: user.id,
            })
            .select()
            .single();

          // Create adjustment record
          await supabase
            .from("cycle_count_adjustments")
            .insert({
              cycle_count_id: countId,
              cycle_count_item_id: item.id,
              adjustment_type: item.variance_quantity > 0 ? 'increase' : 'decrease',
              adjustment_quantity: Math.abs(item.variance_quantity),
              adjustment_value: item.variance_value,
              reason: item.variance_reason || 'Cycle count variance',
              stock_transaction_id: transaction?.id,
              approved_by: user.id,
              approved_date: new Date().toISOString(),
              created_by: user.id,
            });

          // Update item status
          await supabase
            .from("cycle_count_items")
            .update({ status: 'adjusted' })
            .eq("id", item.id);
        }
      }
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["cycle-counts"] });
      queryClient.invalidateQueries({ queryKey: ["cycle-count-items"] });
      queryClient.invalidateQueries({ queryKey: ["warehouse-items"] });
      queryClient.invalidateQueries({ queryKey: ["stock-transactions"] });
      toast({
        title: "Adjustments Posted",
        description: "Stock adjustments posted successfully.",
      });
    },
    onError: (error) => {
      console.error("Post adjustments error:", error);
      toast({
        title: "Error",
        description: "Failed to post adjustments.",
        variant: "destructive",
      });
    },
  });
};
