import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { getCachedUser } from "@/lib/currentUser";
import { useToast } from '@/hooks/use-toast';
import { untypedRpc } from '@/lib/untypedRpc';
import { 
  DeliveryOrder, 
  DeliveryOrderWithDetails,
  CreateDeliveryOrderData,
  DeliveryOrderItem,
  CreateDeliveryOrderItemData
} from '@/types/pickPack';

export const useDeliveryOrders = () => {
  const { toast } = useToast();
  const queryClient = useQueryClient();

  // Fetch all delivery orders
  const useDeliveryOrdersQuery = (companyId?: string) => {
    return useQuery({
      queryKey: ['delivery-orders', companyId],
      queryFn: async () => {
        let query = supabase
          .from('delivery_orders')
          .select(`
            *,
            customer:customers(id, customer_name, customer_code),
            sales_order:sales_orders(id, order_number, status),
            packing_list:packing_lists(id, packing_list_number),
            items:delivery_order_items(
              *,
              finished_good:finished_goods(id, product_name, product_code)
            )
          `)
          .order('created_at', { ascending: false });

        if (companyId) {
          query = query.eq('company_id', companyId);
        }

        const { data, error } = await query;
        if (error) throw error;
        return data as DeliveryOrderWithDetails[];
      },
      enabled: !!companyId,
    });
  };

  // Fetch single delivery order
  const useDeliveryOrder = (doId: string) => {
    return useQuery({
      queryKey: ['delivery-order', doId],
      queryFn: async () => {
        const { data, error } = await supabase
          .from('delivery_orders')
          .select(`
            *,
            customer:customers(*),
            sales_order:sales_orders(*),
            packing_list:packing_lists(*),
            items:delivery_order_items(
              *,
              finished_good:finished_goods(*),
              sales_order_item:sales_order_items(*)
            )
          `)
          .eq('id', doId)
          .single();

        if (error) throw error;
        return data as DeliveryOrderWithDetails;
      },
      enabled: !!doId,
    });
  };

  // Fetch delivery orders by sales order
  const useDeliveryOrdersBySalesOrder = (salesOrderId: string) => {
    return useQuery({
      queryKey: ['delivery-orders-by-so', salesOrderId],
      queryFn: async () => {
        const { data, error } = await supabase
          .from('delivery_orders')
          .select('*, items:delivery_order_items(*)')
          .eq('sales_order_id', salesOrderId)
          .order('created_at', { ascending: false });

        if (error) throw error;
        return data as DeliveryOrderWithDetails[];
      },
      enabled: !!salesOrderId,
    });
  };

  // Create delivery order with items
  const createDeliveryOrderWithItems = useMutation({
    mutationFn: async ({ 
      deliveryOrderData, 
      items 
    }: { 
      deliveryOrderData: CreateDeliveryOrderData; 
      items: CreateDeliveryOrderItemData[] 
    }) => {
      const user = getCachedUser();
      if (!user) throw new Error('User not authenticated');

      // 1. Create delivery order
      const { data: deliveryOrder, error: doError } = await supabase
        .from('delivery_orders')
        .insert([{
          ...deliveryOrderData,
          created_by: user.id,
          do_number: '', // Will be auto-generated by trigger
        }])
        .select()
        .single();

      if (doError) throw doError;

      // 2. Create delivery order items
      const itemsWithDoId = items.map(item => ({
        ...item,
        do_id: deliveryOrder.id,
      }));

      const { error: itemsError } = await supabase
        .from('delivery_order_items')
        .insert(itemsWithDoId);

      if (itemsError) throw itemsError;

      // 3. Update delivery order totals
      const { error: updateError } = await supabase
        .from('delivery_orders')
        .update({
          total_packages: items.length,
        })
        .eq('id', deliveryOrder.id);

      if (updateError) throw updateError;

      return deliveryOrder;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ['delivery-orders'] });
      queryClient.invalidateQueries({ queryKey: ['sales-orders'] });
      toast({
        title: "Success",
        description: `Delivery Order ${data.do_number} created successfully`,
      });
    },
    onError: (error: any) => {
      toast({
        title: "Error",
        description: error.message || "Failed to create delivery order",
        variant: "destructive",
      });
    },
  });

  // Update delivery order status
  const updateDeliveryOrderStatus = useMutation({
    mutationFn: async ({ 
      doId, 
      status, 
      notes 
    }: { 
      doId: string; 
      status: string; 
      notes?: string 
    }) => {
      const updateData: any = { 
        status, 
        updated_at: new Date().toISOString() 
      };

      if (status === 'approved') {
        const user = getCachedUser();
        updateData.approved_by = user?.id;
        updateData.approved_date = new Date().toISOString();
        if (notes) updateData.approval_notes = notes;
      }

      const { data, error } = await supabase
        .from('delivery_orders')
        .update(updateData)
        .eq('id', doId)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['delivery-orders'] });
      toast({
        title: "Success",
        description: "Delivery order status updated successfully",
      });
    },
    onError: (error: any) => {
      toast({
        title: "Error",
        description: error.message || "Failed to update delivery order",
        variant: "destructive",
      });
    },
  });

  // Update delivery order
  const updateDeliveryOrder = useMutation({
    mutationFn: async ({ 
      doId, 
      updates 
    }: { 
      doId: string; 
      updates: Partial<DeliveryOrder> 
    }) => {
      const { data, error } = await supabase
        .from('delivery_orders')
        .update({ ...updates, updated_at: new Date().toISOString() })
        .eq('id', doId)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['delivery-orders'] });
      toast({
        title: "Success",
        description: "Delivery order updated successfully",
      });
    },
    onError: (error: any) => {
      toast({
        title: "Error",
        description: error.message || "Failed to update delivery order",
        variant: "destructive",
      });
    },
  });

  // Cancel delivery order
  const cancelDeliveryOrder = useMutation({
    mutationFn: async ({ doId, notes }: { doId: string; notes?: string }) => {
      const updateData: any = { 
        status: 'cancelled', 
        updated_at: new Date().toISOString() 
      };
      
      // delivery_orders has no "notes" column; the reason goes with the internal notes.
      if (notes) updateData.internal_notes = notes;

      const { data, error } = await supabase
        .from('delivery_orders')
        .update(updateData)
        .eq('id', doId)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['delivery-orders'] });
      queryClient.invalidateQueries({ queryKey: ['sales-orders'] });
      toast({
        title: "Success",
        description: "Delivery order cancelled successfully",
      });
    },
    onError: (error: any) => {
      toast({
        title: "Error",
        description: error.message || "Failed to cancel delivery order",
        variant: "destructive",
      });
    },
  });

  // Delete delivery order
  const deleteDeliveryOrder = useMutation({
    mutationFn: async (doId: string) => {
      const { error } = await supabase
        .from('delivery_orders')
        .delete()
        .eq('id', doId);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['delivery-orders'] });
      toast({
        title: "Success",
        description: "Delivery order deleted successfully",
      });
    },
    onError: (error: any) => {
      toast({
        title: "Error",
        description: error.message || "Failed to delete delivery order",
        variant: "destructive",
      });
    },
  });

  const refreshAfterDelivery = () => {
    for (const key of ['delivery-orders', 'delivery-order', 'sales-orders', 'customer-purchase-orders', 'customer-purchase-order']) {
      queryClient.invalidateQueries({ queryKey: [key] });
    }
  };

  // Approved → in transit; the sales order lines record what was dispatched.
  const dispatchDeliveryOrder = useMutation({
    mutationFn: (doId: string) => untypedRpc<null>('dispatch_delivery_order', { p_do_id: doId }),
    onSuccess: () => {
      refreshAfterDelivery();
      toast({ title: 'Dispatched', description: 'The delivery order is in transit.' });
    },
    onError: (error: Error) => toast({ title: 'Error', description: error.message, variant: 'destructive' }),
  });

  // In transit (or approved) → delivered; the sales order and customer PO follow.
  const confirmDelivery = useMutation({
    mutationFn: (v: { doId: string; receivedBy: string; deliveredAt: string; lines: { item_id: string; quantity_delivered: number }[]; remarks?: string }) =>
      untypedRpc<string>('confirm_delivery', {
        p_do_id: v.doId,
        p_received_by: v.receivedBy,
        p_delivered_at: v.deliveredAt,
        p_lines: v.lines,
        p_remarks: v.remarks || null,
      }),
    onSuccess: () => {
      refreshAfterDelivery();
      toast({ title: 'Delivery confirmed' });
    },
    onError: (error: Error) => toast({ title: 'Error', description: error.message, variant: 'destructive' }),
  });

  return {
    useDeliveryOrdersQuery,
    dispatchDeliveryOrder: dispatchDeliveryOrder.mutate,
    isDispatching: dispatchDeliveryOrder.isPending,
    confirmDelivery: confirmDelivery.mutate,
    isConfirmingDelivery: confirmDelivery.isPending,
    useDeliveryOrder,
    useDeliveryOrdersBySalesOrder,
    createDeliveryOrderWithItems: createDeliveryOrderWithItems.mutate,
    isCreatingDeliveryOrder: createDeliveryOrderWithItems.isPending,
    updateDeliveryOrderStatus: updateDeliveryOrderStatus.mutate,
    isUpdatingStatus: updateDeliveryOrderStatus.isPending,
    updateDeliveryOrder: updateDeliveryOrder.mutate,
    isUpdating: updateDeliveryOrder.isPending,
    cancelDeliveryOrder: cancelDeliveryOrder.mutate,
    isCancelling: cancelDeliveryOrder.isPending,
    deleteDeliveryOrder: deleteDeliveryOrder.mutate,
    isDeleting: deleteDeliveryOrder.isPending,
  };
};