import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { GoodsReceiptNote, CreateGrnData, GrnSummary } from '@/types/grn';
import { useToast } from '@/hooks/use-toast';

export const useGoodsReceiptNotes = (companyId?: string) => {
  return useQuery({
    queryKey: ['goods-receipt-notes', companyId],
    queryFn: async () => {
      let query = supabase
        .from('goods_receipt_notes')
        .select(`
          *,
          purchase_order:purchase_orders(po_number, supplier:suppliers(name)),
          created_by_profile:profiles!goods_receipt_notes_created_by_profile_fkey(full_name),
          received_by_profile:profiles!goods_receipt_notes_received_by_profile_fkey(full_name),
          approved_by_profile:profiles!goods_receipt_notes_approved_by_profile_fkey(full_name),
          grn_items(
            id,
            grn_id,
            item_code,
            item_name,
            description,
            warehouse_item_id,
            po_item_id,
            quantity_ordered,
            quantity_received,
            unit_of_measure,
            unit_price,
            total_cost,
            quality_status,
            remarks,
            created_at,
            updated_at
          )
        `)
        .order('created_at', { ascending: false });

      if (companyId) {
        query = query.eq('company_id', companyId);
      }

      const { data, error } = await query;

      if (error) throw error;
      return data as any;
    },
    enabled: !!companyId,
  });
};

export const useGrnById = (id: string) => {
  return useQuery({
    queryKey: ['goods-receipt-note', id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('goods_receipt_notes')
        .select(`
          *,
          purchase_order:purchase_orders(po_number, supplier:suppliers(name)),
          created_by_profile:profiles!goods_receipt_notes_created_by_profile_fkey(full_name),
          received_by_profile:profiles!goods_receipt_notes_received_by_profile_fkey(full_name),
          approved_by_profile:profiles!goods_receipt_notes_approved_by_profile_fkey(full_name),
          grn_items(
            id,
            grn_id,
            item_code,
            item_name,
            description,
            warehouse_item_id,
            po_item_id,
            quantity_ordered,
            quantity_received,
            unit_of_measure,
            unit_price,
            total_cost,
            quality_status,
            remarks,
            created_at,
            updated_at
          )
        `)
        .eq('id', id)
        .single();

      if (error) throw error;
      return data as any;
    },
    enabled: !!id,
  });
};

export const useGrnSummary = (companyId?: string) => {
  return useQuery({
    queryKey: ['grn-summary', companyId],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('goods_receipt_notes')
        .select('id, status, total_value, created_at')
        .eq('company_id', companyId || '');

      if (error) throw error;

      const currentMonth = new Date().getMonth();
      const currentYear = new Date().getFullYear();

      const summary: GrnSummary = {
        total_grns: data.length,
        pending_approval: data.filter(g => g.status === 'submitted').length,
        approved_this_month: data.filter(g => {
          const grnDate = new Date(g.created_at);
          return g.status === 'approved' && 
                 grnDate.getMonth() === currentMonth && 
                 grnDate.getFullYear() === currentYear;
        }).length,
        total_value: data.reduce((sum, g) => sum + (g.total_value || 0), 0),
      };

      return summary;
    },
    enabled: !!companyId,
  });
};

export const useCreateGoodsReceiptNote = () => {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async (data: CreateGrnData) => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('Not authenticated');

      // Create GRN header (grn_number is auto-generated by trigger)
      const { data: grn, error: grnError } = await supabase
        .from('goods_receipt_notes')
        .insert({
          grn_date: data.grn_date,
          po_id: data.po_id || null,
          po_number: data.po_number || null,
          supplier_id: data.supplier_id || null,
          supplier_name: data.supplier_name || null,
          supplier_address: data.supplier_address || null,
          invoice_number: data.invoice_number,
          invoice_date: data.invoice_date,
          invoice_document_url: data.invoice_document_url,
          remarks: data.remarks,
          status: data.status,
          company_id: data.company_id || null,
          created_by: user.id,
        } as any)
        .select()
        .single();

      if (grnError) throw grnError;

      // Look up warehouse_item_id for items that have item_code but no warehouse_item_id
      const enrichedItems = await Promise.all(
        data.items.map(async (item) => {
          let warehouseItemId = item.warehouse_item_id;
          
          // If no warehouse_item_id but has item_code, look it up
          if (!warehouseItemId && item.item_code) {
            const { data: warehouseItem } = await supabase
              .from('warehouse_items')
              .select('id')
              .eq('item_code', item.item_code)
              .or(`company_id.eq.${data.company_id},company_id.is.null`)
              .limit(1)
              .maybeSingle();
            
            if (warehouseItem) {
              warehouseItemId = warehouseItem.id;
            }
          }
          
          return {
            grn_id: grn.id,
            po_item_id: item.po_item_id,
            warehouse_item_id: warehouseItemId,
            item_code: item.item_code,
            item_name: item.item_name,
            description: item.description,
            unit_of_measure: item.unit_of_measure,
            quantity_ordered: item.quantity_ordered,
            quantity_received: item.quantity_received,
            unit_price: item.unit_price,
            total_cost: item.total_cost,
            quality_status: item.quality_status,
            remarks: item.remarks,
            // Batch tracking fields
            batch_number: item.batch_number || null,
            manufacturing_date: item.manufacturing_date || null,
            expiry_date: item.expiry_date || null,
          };
        })
      );

      const { error: itemsError } = await supabase
        .from('grn_items')
        .insert(enrichedItems);

      if (itemsError) throw itemsError;

      return grn;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['goods-receipt-notes'] });
      queryClient.invalidateQueries({ queryKey: ['grn-summary'] });
      queryClient.invalidateQueries({ queryKey: ['purchase-orders'] });
      queryClient.invalidateQueries({ queryKey: ['warehouse-items'] });
      queryClient.invalidateQueries({ queryKey: ['stock-transactions'] });
      toast({
        title: 'Success',
        description: 'Goods Receipt Note created successfully',
      });
    },
    onError: (error: Error) => {
      toast({
        title: 'Error',
        description: error.message,
        variant: 'destructive',
      });
    },
  });
};

export const useUpdateGoodsReceiptNote = () => {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async ({ id, data }: { id: string; data: Partial<CreateGrnData> }) => {
      const { error } = await supabase
        .from('goods_receipt_notes')
        .update({
          grn_date: data.grn_date,
          invoice_number: data.invoice_number,
          invoice_date: data.invoice_date,
          status: data.status,
          remarks: data.remarks,
        })
        .eq('id', id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['goods-receipt-notes'] });
      queryClient.invalidateQueries({ queryKey: ['goods-receipt-note'] });
      queryClient.invalidateQueries({ queryKey: ['grn-summary'] });
      toast({
        title: 'Success',
        description: 'GRN updated successfully',
      });
    },
    onError: (error: Error) => {
      toast({
        title: 'Error',
        description: error.message,
        variant: 'destructive',
      });
    },
  });
};

export const useSubmitGoodsReceiptNote = () => {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase
        .from('goods_receipt_notes')
        .update({ status: 'submitted' })
        .eq('id', id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['goods-receipt-notes'] });
      queryClient.invalidateQueries({ queryKey: ['goods-receipt-note'] });
      queryClient.invalidateQueries({ queryKey: ['grn-summary'] });
      toast({
        title: 'Success',
        description: 'GRN submitted for approval',
      });
    },
    onError: (error: Error) => {
      toast({
        title: 'Error',
        description: error.message,
        variant: 'destructive',
      });
    },
  });
};

export interface GrnBinAllocationInput {
  warehouse_item_id: string;
  bin_id: string;
  quantity: number;
}

export const useApproveGoodsReceiptNote = () => {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async ({ id, binAllocations }: { id: string; binAllocations: GrnBinAllocationInput[] }) => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('Not authenticated');

      // Get the GRN with items and grn_number
      const { data: grn, error: grnFetchError } = await supabase
        .from('goods_receipt_notes')
        .select('company_id, grn_number, grn_items(id, warehouse_item_id, quantity_received, unit_price, total_cost, item_name)')
        .eq('id', id)
        .single();

      if (grnFetchError) throw grnFetchError;

      // Fetch current stock levels BEFORE the approval trigger fires
      const itemsWithStock: Array<{
        warehouse_item_id: string;
        quantity_received: number;
        unit_price: number;
        total_cost: number;
        item_name: string;
        quantity_before: number;
      }> = [];

      const grnItems = (grn as any).grn_items || [];
      for (const item of grnItems) {
        if (!item.warehouse_item_id) continue;
        const { data: whItem } = await supabase
          .from('warehouse_items')
          .select('current_stock')
          .eq('id', item.warehouse_item_id)
          .single();

        itemsWithStock.push({
          warehouse_item_id: item.warehouse_item_id,
          quantity_received: item.quantity_received || 0,
          unit_price: item.unit_price || 0,
          total_cost: item.total_cost || 0,
          item_name: item.item_name || '',
          quantity_before: whItem?.current_stock || 0,
        });
      }

      // Update GRN status to approved
      // The database trigger 'update_stock_on_grn_approval' handles updating warehouse_items.current_stock
      const { error: approveError } = await supabase
        .from('goods_receipt_notes')
        .update({
          status: 'approved',
          approved_by: user.id,
          approved_date: new Date().toISOString(),
        })
        .eq('id', id);

      if (approveError) throw approveError;

      // Insert stock transaction records for movement history
      if (itemsWithStock.length > 0) {
        const stockTransactions = itemsWithStock.map((item) => ({
          item_id: item.warehouse_item_id,
          transaction_type: 'goods_receipt' as const,
          reference_type: 'grn' as const,
          reference_id: id,
          quantity_change: item.quantity_received,
          quantity_before: item.quantity_before,
          quantity_after: item.quantity_before + item.quantity_received,
          unit_cost: item.unit_price,
          total_value: item.total_cost,
          notes: `GRN ${(grn as any).grn_number} - ${item.item_name}`,
          company_id: grn.company_id,
          created_by: user.id,
        }));

        const { error: txError } = await supabase
          .from('stock_transactions')
          .insert(stockTransactions);

        if (txError) throw txError;
      }

      // Process bin allocations
      for (const alloc of binAllocations) {
        // Check if allocation already exists for this item+bin+company
        const { data: existing } = await supabase
          .from('warehouse_bin_allocations')
          .select('id, allocated_quantity')
          .eq('warehouse_item_id', alloc.warehouse_item_id)
          .eq('bin_id', alloc.bin_id)
          .eq('company_id', grn.company_id)
          .maybeSingle();

        if (existing) {
          // Increment existing allocation
          const { error: updateError } = await supabase
            .from('warehouse_bin_allocations')
            .update({
              allocated_quantity: (existing.allocated_quantity || 0) + alloc.quantity,
              updated_at: new Date().toISOString(),
            })
            .eq('id', existing.id);

          if (updateError) throw updateError;
        } else {
          // Insert new allocation
          const { error: insertError } = await supabase
            .from('warehouse_bin_allocations')
            .insert({
              warehouse_item_id: alloc.warehouse_item_id,
              bin_id: alloc.bin_id,
              allocated_quantity: alloc.quantity,
              company_id: grn.company_id,
              created_by: user.id,
            });

          if (insertError) throw insertError;
        }

        // Increment bin's current_quantity
        const { data: binData } = await supabase
          .from('warehouse_bins')
          .select('current_quantity')
          .eq('id', alloc.bin_id)
          .single();

        if (binData) {
          const { error: binUpdateError } = await supabase
            .from('warehouse_bins')
            .update({
              current_quantity: (binData.current_quantity || 0) + alloc.quantity,
            })
            .eq('id', alloc.bin_id);

          if (binUpdateError) throw binUpdateError;
        }
      }
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['goods-receipt-notes'] });
      queryClient.invalidateQueries({ queryKey: ['goods-receipt-note'] });
      queryClient.invalidateQueries({ queryKey: ['grn-summary'] });
      queryClient.invalidateQueries({ queryKey: ['warehouse-items'] });
      queryClient.invalidateQueries({ queryKey: ['stock-transactions'] });
      queryClient.invalidateQueries({ queryKey: ['warehouse-bins'] });
      queryClient.invalidateQueries({ queryKey: ['warehouse-bin-allocations'] });
      toast({
        title: 'Success',
        description: 'GRN approved and stock allocated to bins successfully.',
      });
    },
    onError: (error: Error) => {
      toast({
        title: 'Error',
        description: error.message,
        variant: 'destructive',
      });
    },
  });
};

export const useDeleteGoodsReceiptNote = () => {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async (id: string) => {
      // Delete items first
      const { error: itemsError } = await supabase
        .from('grn_items')
        .delete()
        .eq('grn_id', id);

      if (itemsError) throw itemsError;

      // Delete GRN
      const { error } = await supabase
        .from('goods_receipt_notes')
        .delete()
        .eq('id', id)
        .eq('status', 'draft');

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['goods-receipt-notes'] });
      queryClient.invalidateQueries({ queryKey: ['grn-summary'] });
      toast({
        title: 'Success',
        description: 'GRN deleted successfully',
      });
    },
    onError: (error: Error) => {
      toast({
        title: 'Error',
        description: error.message,
        variant: 'destructive',
      });
    },
  });
};
