import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { getCachedUser, ensureUserId } from "@/lib/currentUser";
import { MaterialRequest, CreateMaterialRequestData } from '@/types/materialIssueReturn';
import { useToast } from '@/hooks/use-toast';
import { useCompany } from '@/contexts/CompanyContext';
import { useLocationFilter } from '@/contexts/LocationFilterContext';

export const useMaterialRequests = () => {
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const { selectedCompany } = useCompany();
  const { globalLocationId } = useLocationFilter();
  const companyId = selectedCompany?.id ?? null;

  // Fetch material requests scoped to selected company + (optional) global location
  const { data: materialRequests, isLoading, error } = useQuery({
    queryKey: ['material-requests', companyId, globalLocationId],
    enabled: !!companyId,
    queryFn: async () => {
      let query = supabase
        .from('material_requests')
        .select('*, warehouse_locations(name)')
        .eq('company_id', companyId as string)
        .order('created_at', { ascending: false });

      if (globalLocationId) {
        query = query.eq('location_id', globalLocationId);
      }

      const { data, error } = await query;
      if (error) throw error;
      return data as MaterialRequest[];
    },
  });

  // Create material request
  const createRequestMutation = useMutation({
    mutationFn: async (requestData: CreateMaterialRequestData) => {
      const userId = getCachedUser()?.id ?? (await ensureUserId());
      if (!userId) throw new Error('You are signed out. Please sign in again and retry.');

      const resolvedCompanyId = requestData.company_id || companyId;
      if (!resolvedCompanyId) throw new Error('No company selected. Pick a company before creating a request.');

      // Normalize empty-string form values: uuid/date columns reject '' outright,
      // and NULL company_id/location_id makes the row invisible to RLS afterwards.
      const clean = (v?: string | null) => {
        const t = typeof v === 'string' ? v.trim() : v;
        return t ? t : null;
      };

      const payload = {
        ...requestData,
        request_number: '', // Auto-generated by trigger
        company_id: resolvedCompanyId,
        location_id: clean(requestData.location_id),
        cpo_id: clean(requestData.cpo_id),
        cpo_number: clean(requestData.cpo_number),
        srn_number: clean(requestData.srn_number),
        department: clean((requestData as { department?: string }).department),
        contact_number: clean(requestData.contact_number),
        epf_number: clean(requestData.epf_number),
        job_number: clean(requestData.job_number),
        notes: clean(requestData.notes),
        items_required_date: clean(requestData.items_required_date),
        created_by: userId,
      };

      if (!payload.items_required_date) throw new Error('Date required is missing.');
      if (!payload.location_id) throw new Error('Please select a location for this request.');

      const { data, error } = await supabase
        .from('material_requests')
        .insert([payload])
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['material-requests'] });
      toast({
        title: "Success",
        description: "Material request created successfully",
      });
    },
    onError: (error: any) => {
      console.error('Error creating material request:', error);
      toast({
        title: "Error",
        description: error?.message ?? "Failed to create material request",
        variant: "destructive",
      });
    }
  });


  // Update material request
  const updateRequestMutation = useMutation({
    mutationFn: async ({ id, ...data }: Partial<MaterialRequest> & { id: string }) => {
      const { error } = await supabase
        .from('material_requests')
        .update(data)
        .eq('id', id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['material-requests'] });
      toast({
        title: "Success",
        description: "Material request updated successfully",
      });
    },
    onError: (error) => {
      console.error('Error updating material request:', error);
      toast({
        title: "Error",
        description: "Failed to update material request",
        variant: "destructive",
      });
    }
  });

  // Submit for approval (draft -> pending_hod_approval)
  const submitForApprovalMutation = useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase
        .from('material_requests')
        .update({ status: 'pending_hod_approval' })
        .eq('id', id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['material-requests'] });
      toast({
        title: "Success",
        description: "Material request submitted for approval",
      });
    },
    onError: (error) => {
      console.error('Error submitting request:', error);
      toast({
        title: "Error",
        description: "Failed to submit material request",
        variant: "destructive",
      });
    }
  });

  // HOD approval
  const hodApproveMutation = useMutation({
    mutationFn: async ({ id, comments, requiresManagementApproval }: { 
      id: string; 
      comments?: string;
      requiresManagementApproval?: boolean;
    }) => {
      const user = getCachedUser();
      
      const { error } = await supabase
        .from('material_requests')
        .update({
          status: requiresManagementApproval ? 'pending_management_approval' : 'approved',
          hod_approved_by: user?.id,
          hod_approval_date: new Date().toISOString(),
          hod_comments: comments,
        })
        .eq('id', id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['material-requests'] });
      toast({
        title: "Success",
        description: "Material request approved by HOD",
      });
    },
    onError: (error) => {
      console.error('Error approving request:', error);
      toast({
        title: "Error",
        description: "Failed to approve material request",
        variant: "destructive",
      });
    }
  });

  // Management approval
  const managementApproveMutation = useMutation({
    mutationFn: async ({ id, comments }: { id: string; comments?: string }) => {
      const user = getCachedUser();
      
      const { error } = await supabase
        .from('material_requests')
        .update({
          status: 'approved',
          management_approved_by: user?.id,
          management_approval_date: new Date().toISOString(),
          management_comments: comments,
        })
        .eq('id', id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['material-requests'] });
      toast({
        title: "Success",
        description: "Material request approved by Management",
      });
    },
    onError: (error) => {
      console.error('Error approving request:', error);
      toast({
        title: "Error",
        description: "Failed to approve material request",
        variant: "destructive",
      });
    }
  });

  // Reject request
  const rejectRequestMutation = useMutation({
    mutationFn: async ({ id, reason }: { id: string; reason: string }) => {
      const { error } = await supabase
        .from('material_requests')
        .update({
          status: 'rejected',
          rejection_reason: reason,
        })
        .eq('id', id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['material-requests'] });
      toast({
        title: "Success",
        description: "Material request rejected",
      });
    },
    onError: (error) => {
      console.error('Error rejecting request:', error);
      toast({
        title: "Error",
        description: "Failed to reject material request",
        variant: "destructive",
      });
    }
  });

  // Delete material request
  const deleteRequestMutation = useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase
        .from('material_requests')
        .delete()
        .eq('id', id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['material-requests'] });
      toast({
        title: "Success",
        description: "Material request deleted successfully",
      });
    },
    onError: (error) => {
      console.error('Error deleting material request:', error);
      toast({
        title: "Error",
        description: "Failed to delete material request",
        variant: "destructive",
      });
    }
  });

  return {
    materialRequests,
    isLoading,
    error,
    createRequest: createRequestMutation.mutate,
    createRequestAsync: createRequestMutation.mutateAsync,
    isCreating: createRequestMutation.isPending,
    updateRequest: updateRequestMutation.mutate,
    isUpdating: updateRequestMutation.isPending,
    submitForApproval: submitForApprovalMutation.mutate,
    isSubmitting: submitForApprovalMutation.isPending,
    hodApprove: hodApproveMutation.mutate,
    isHodApproving: hodApproveMutation.isPending,
    managementApprove: managementApproveMutation.mutate,
    isManagementApproving: managementApproveMutation.isPending,
    rejectRequest: rejectRequestMutation.mutate,
    isRejecting: rejectRequestMutation.isPending,
    deleteRequest: deleteRequestMutation.mutate,
    isDeleting: deleteRequestMutation.isPending,
  };
};
