import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { getCachedUser } from "@/lib/currentUser";
import { PutawayRecord, PutawayItem, CreatePutawayRecordData, CreatePutawayItemData } from '@/types/putaway';
import { useToast } from '@/hooks/use-toast';

export const usePutawayRecords = (status?: string) => {
  const { toast } = useToast();

  return useQuery({
    queryKey: ['putaway-records', status],
    queryFn: async () => {
      let query = supabase
        .from('putaway_records')
        .select('*')
        .order('created_at', { ascending: false });

      if (status) {
        query = query.eq('status', status);
      }

      const { data, error } = await query;
      if (error) throw error;
      return data as PutawayRecord[];
    }
  });
};

export const usePutawayItems = (putawayId: string) => {
  return useQuery({
    queryKey: ['putaway-items', putawayId],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('putaway_items')
        .select('*')
        .eq('putaway_id', putawayId)
        .order('putaway_sequence', { ascending: true });

      if (error) throw error;
      return data as PutawayItem[];
    },
    enabled: !!putawayId
  });
};

export const useCreatePutaway = () => {
  const { toast } = useToast();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (putawayData: CreatePutawayRecordData) => {
      const user = getCachedUser();
      if (!user) throw new Error('User not authenticated');

      const { data, error } = await supabase
        .from('putaway_records')
        .insert([{
          putaway_number: '', // Will be auto-generated by trigger
          ...putawayData,
          created_by: user.id
        }])
        .select()
        .single();

      if (error) throw error;
      return data as PutawayRecord;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['putaway-records'] });
      toast({
        title: "Success",
        description: "Putaway created successfully",
      });
    },
    onError: (error) => {
      console.error('Error creating putaway:', error);
      toast({
        title: "Error",
        description: "Failed to create putaway",
        variant: "destructive",
      });
    }
  });
};

export const useCreatePutawayItem = () => {
  const { toast } = useToast();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (itemData: CreatePutawayItemData) => {
      const { data, error } = await supabase
        .from('putaway_items')
        .insert(itemData)
        .select()
        .single();

      if (error) throw error;
      return data as PutawayItem;
    },
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ['putaway-items', variables.putaway_id] });
    },
    onError: (error) => {
      console.error('Error creating putaway item:', error);
      toast({
        title: "Error",
        description: "Failed to add item to putaway",
        variant: "destructive",
      });
    }
  });
};

export const useUpdatePutaway = () => {
  const { toast } = useToast();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ id, updates }: { id: string; updates: Partial<PutawayRecord> }) => {
      const { data, error } = await supabase
        .from('putaway_records')
        .update(updates)
        .eq('id', id)
        .select()
        .single();

      if (error) throw error;
      return data as PutawayRecord;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['putaway-records'] });
      toast({
        title: "Success",
        description: "Putaway updated successfully",
      });
    },
    onError: (error) => {
      console.error('Error updating putaway:', error);
      toast({
        title: "Error",
        description: "Failed to update putaway",
        variant: "destructive",
      });
    }
  });
};

export const useUpdatePutawayItem = () => {
  const { toast } = useToast();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ id, putawayId, updates }: { 
      id: string; 
      putawayId: string;
      updates: Partial<PutawayItem> 
    }) => {
      const { data, error } = await supabase
        .from('putaway_items')
        .update(updates)
        .eq('id', id)
        .select()
        .single();

      if (error) throw error;
      return data as PutawayItem;
    },
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ['putaway-items', variables.putawayId] });
    },
    onError: (error) => {
      console.error('Error updating putaway item:', error);
      toast({
        title: "Error",
        description: "Failed to update item",
        variant: "destructive",
      });
    }
  });
};

export const useCompletePutaway = () => {
  const { toast } = useToast();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (putawayId: string) => {
      const user = getCachedUser();
      if (!user) throw new Error('User not authenticated');

      // Get all pending items
      const { data: items, error: itemsError } = await supabase
        .from('putaway_items')
        .select('*')
        .eq('putaway_id', putawayId)
        .eq('status', 'pending');

      if (itemsError) throw itemsError;

      // Update bin quantities and create stock transactions for each item
      for (const item of items || []) {
        if (item.to_bin_id) {
          // Get current bin quantity
          const { data: binData } = await supabase
            .from('warehouse_bins')
            .select('current_quantity')
            .eq('id', item.to_bin_id)
            .single();

          const currentQuantity = binData?.current_quantity || 0;
          const newQuantity = currentQuantity + item.quantity;

          // Update bin quantity directly
          const { error: binError } = await supabase
            .from('warehouse_bins')
            .update({ current_quantity: newQuantity })
            .eq('id', item.to_bin_id);

          if (binError) {
            console.error('Error updating bin quantity:', binError);
          }

          // Create stock transaction
          const { error: transactionError } = await supabase
            .from('stock_transactions')
            .insert([{
              item_id: item.warehouse_item_id,
              transaction_type: 'transfer_in',
              reference_type: 'transfer',
              reference_id: putawayId,
              quantity_change: item.quantity,
              quantity_before: 0,
              quantity_after: item.quantity,
              notes: `Putaway to bin`,
              created_by: user.id
            }]);

          if (transactionError) {
            console.error('Error creating stock transaction:', transactionError);
          }
        }

        // Mark item as completed
        await supabase
          .from('putaway_items')
          .update({ status: 'completed' })
          .eq('id', item.id);
      }

      // Update putaway record
      const { data, error } = await supabase
        .from('putaway_records')
        .update({
          status: 'completed',
          completed_date: new Date().toISOString(),
          completed_by: user.id
        })
        .eq('id', putawayId)
        .select()
        .single();

      if (error) throw error;
      return data as PutawayRecord;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['putaway-records'] });
      queryClient.invalidateQueries({ queryKey: ['warehouse-bins'] });
      toast({
        title: "Success",
        description: "Putaway completed successfully",
      });
    },
    onError: (error) => {
      console.error('Error completing putaway:', error);
      toast({
        title: "Error",
        description: "Failed to complete putaway",
        variant: "destructive",
      });
    }
  });
};

export const useDeletePutaway = () => {
  const { toast } = useToast();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase
        .from('putaway_records')
        .delete()
        .eq('id', id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['putaway-records'] });
      toast({
        title: "Success",
        description: "Putaway deleted successfully",
      });
    },
    onError: (error) => {
      console.error('Error deleting putaway:', error);
      toast({
        title: "Error",
        description: "Failed to delete putaway",
        variant: "destructive",
      });
    }
  });
};
