import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';
import { 
  SalesOrder, 
  CreateSalesOrderData, 
  PickList, 
  CreatePickListData, 
  PickListItem,
  CreatePickListItemData,
  SalesOrderWithDetails,
  PickListWithDetails 
} from '@/types/pickPack';

export const usePickPack = () => {
  const { toast } = useToast();
  const queryClient = useQueryClient();

  // Fetch confirmed Customer Purchase Orders ready for fulfillment
  const useConfirmedCPOs = () => {
    return useQuery({
      queryKey: ['confirmed-cpos'],
      queryFn: async () => {
        const { data, error } = await supabase
          .from('customer_purchase_orders')
          .select(`
            *,
            customers (
              id,
              customer_name,
              customer_code
            ),
            customer_po_items (
              *,
              finished_goods (
                id,
                product_name,
                product_code,
                current_stock,
                available_stock
              )
            )
          `)
          .eq('status', 'confirmed')
          .order('created_at', { ascending: false });

        if (error) throw error;
        return data || [];
      }
    });
  };

  // Fetch Sales Orders
  const useSalesOrders = () => {
    return useQuery({
      queryKey: ['sales-orders'],
      queryFn: async () => {
        const { data, error } = await supabase
          .from('sales_orders')
          .select(`
            *,
            customer:customers (
              id,
              customer_name,
              customer_code
            ),
            cpo:customer_purchase_orders!cpo_id (
              id,
              cpo_number,
              total_amount
            )
          `)
          .order('created_at', { ascending: false });

        if (error) throw error;
        return data as SalesOrderWithDetails[];
      }
    });
  };

  // Fetch Pick Lists
  const usePickLists = (status?: string) => {
    return useQuery({
      queryKey: ['pick-lists', status],
      queryFn: async () => {
        let query = supabase
          .from('pick_lists')
          .select(`
            *,
            sales_order:sales_orders!sales_order_id (
              id,
              order_number,
              customer_id,
              customer:customers (
                customer_name,
                customer_code
              )
            ),
            picker:profiles!picker_id (
              id,
              full_name
            )
          `)
          .order('created_at', { ascending: false });

        if (status) {
          query = query.eq('status', status);
        }

        const { data, error } = await query;
        if (error) throw error;
        return data as any[];
      }
    });
  };

  // Fetch Pick List Items
  const usePickListItems = (pickListId: string) => {
    return useQuery({
      queryKey: ['pick-list-items', pickListId],
      queryFn: async () => {
        const { data, error } = await supabase
          .from('pick_list_items')
          .select(`
            *,
            finished_goods (
              id,
              product_name,
              product_code,
              current_stock
            ),
            warehouse_locations!location_id (
              id,
              name
            ),
            warehouse_bins!bin_id (
              id,
              bin_number
            )
          `)
          .eq('pick_list_id', pickListId)
          .order('pick_sequence', { ascending: true });

        if (error) throw error;
        return data;
      },
      enabled: !!pickListId
    });
  };

  // Create Sales Order from CPO
  const createSalesOrderMutation = useMutation({
    mutationFn: async (data: CreateSalesOrderData) => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('User not authenticated');

      const { data: salesOrder, error } = await supabase
        .from('sales_orders')
        .insert([{
          ...data,
          order_number: '', // Will be auto-generated by trigger
          created_by: user.id
        }])
        .select()
        .single();

      if (error) throw error;
      return salesOrder;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['sales-orders'] });
      toast({
        title: "Success",
        description: "Sales order created successfully",
      });
    },
    onError: (error) => {
      console.error('Error creating sales order:', error);
      toast({
        title: "Error",
        description: "Failed to create sales order",
        variant: "destructive",
      });
    }
  });

  // Create Pick List
  const createPickListMutation = useMutation({
    mutationFn: async (data: CreatePickListData) => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('User not authenticated');

      const { data: pickList, error } = await supabase
        .from('pick_lists')
        .insert([{
          ...data,
          pick_list_number: '', // Will be auto-generated by trigger
          created_by: user.id
        }])
        .select()
        .single();

      if (error) throw error;
      return pickList;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['pick-lists'] });
      toast({
        title: "Success",
        description: "Pick list created successfully",
      });
    },
    onError: (error) => {
      console.error('Error creating pick list:', error);
      toast({
        title: "Error",
        description: "Failed to create pick list",
        variant: "destructive",
      });
    }
  });

  // Create Pick List With Items (auto-generates items from sales order)
  const createPickListWithItemsMutation = useMutation({
    mutationFn: async (pickListData: CreatePickListData & { sales_order_id: string }) => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('User not authenticated');

      const { sales_order_id, ...basePickListData } = pickListData;

      // 1. Fetch sales order items that need picking (issued but not fully picked)
      const { data: soItems, error: soError } = await supabase
        .from('sales_order_items')
        .select('*, finished_goods(*)')
        .eq('sales_order_id', sales_order_id)
        .gt('quantity_issued', 0);

      if (soError) throw soError;
      if (!soItems || soItems.length === 0) {
        throw new Error('No items available to pick for this sales order');
      }

      // Filter items that still need picking
      const itemsNeedingPick = soItems.filter(item => 
        (item.quantity_picked || 0) < item.quantity_issued
      );

      if (itemsNeedingPick.length === 0) {
        throw new Error('All items have already been picked for this sales order');
      }

      // 2. Find stock locations for each item
      const itemsWithLocations = await Promise.all(
        itemsNeedingPick.map(async (item, index) => {
          try {
            // Get finished good details with location
            const { data: fg, error: fgError } = await supabase
              .from('finished_goods')
              .select('id, location_id, bin_id, current_stock, available_stock')
              .eq('id', item.finished_good_id)
              .gt('current_stock', 0)
              .single();

            if (fgError || !fg) {
              console.error(`No stock found for item ${item.id}`);
              return null;
            }

            const quantityToPick = Math.min(
              item.quantity_issued - (item.quantity_picked || 0),
              fg.current_stock || 0
            );

            if (quantityToPick <= 0) {
              return null;
            }

            return {
              sales_order_item_id: item.id,
              finished_good_id: item.finished_good_id,
              location_id: fg.location_id,
              bin_id: fg.bin_id,
              quantity_to_pick: quantityToPick,
              pick_sequence: index + 1,
              status: 'pending' as const
            };
          } catch (error) {
            console.error(`Failed to find stock for item ${item.id}:`, error);
            return null;
          }
        })
      );

      const validItems = itemsWithLocations.filter(item => item !== null);
      
      if (validItems.length === 0) {
        throw new Error('No stock available for any items');
      }

      // 3. Create pick list
      const { data: pickList, error: plError } = await supabase
        .from('pick_lists')
        .insert({
          ...basePickListData,
          sales_order_id,
          total_items: validItems.length,
          pick_list_number: '', // Will be auto-generated by trigger
          created_by: user.id
        })
        .select()
        .single();

      if (plError) throw plError;

      // 4. Create pick list items
      const { error: itemsError } = await supabase
        .from('pick_list_items')
        .insert(
          validItems.map(item => ({
            ...item,
            pick_list_id: pickList.id,
          }))
        );

      if (itemsError) throw itemsError;

      return pickList;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['pick-lists'] });
      queryClient.invalidateQueries({ queryKey: ['sales-orders'] });
      toast({
        title: "Success",
        description: "Pick list created with items successfully",
      });
    },
    onError: (error: Error) => {
      console.error('Error creating pick list:', error);
      toast({
        title: "Error",
        description: error.message || "Failed to create pick list",
        variant: "destructive",
      });
    },
  });

  // Create Pick List Items
  const createPickListItemsMutation = useMutation({
    mutationFn: async (items: CreatePickListItemData[]) => {
      const { data, error } = await supabase
        .from('pick_list_items')
        .insert(items)
        .select();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['pick-list-items'] });
      toast({
        title: "Success",
        description: "Pick list items created successfully",
      });
    },
    onError: (error) => {
      console.error('Error creating pick list items:', error);
      toast({
        title: "Error",
        description: "Failed to create pick list items",
        variant: "destructive",
      });
    }
  });

  // Update Pick List Status
  const updatePickListStatusMutation = useMutation({
    mutationFn: async ({ id, status, pickedBy }: { id: string; status: string; pickedBy?: string }) => {
      const updateData: any = { status };
      
      if (status === 'in_progress') {
        updateData.started_at = new Date().toISOString();
      } else if (status === 'completed') {
        updateData.completed_at = new Date().toISOString();
      }

      if (pickedBy) {
        updateData.picker_id = pickedBy;
      }

      const { data, error } = await supabase
        .from('pick_lists')
        .update(updateData)
        .eq('id', id)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['pick-lists'] });
      toast({
        title: "Success",
        description: "Pick list status updated successfully",
      });
    },
    onError: (error) => {
      console.error('Error updating pick list status:', error);
      toast({
        title: "Error",
        description: "Failed to update pick list status",
        variant: "destructive",
      });
    }
  });

  // Update Pick List Item
  const updatePickListItemMutation = useMutation({
    mutationFn: async ({ 
      id, 
      quantityPicked, 
      status, 
      notes 
    }: { 
      id: string; 
      quantityPicked: number; 
      status: string; 
      notes?: string 
    }) => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('User not authenticated');

      const updateData: any = {
        quantity_picked: quantityPicked,
        status,
        picked_at: new Date().toISOString(),
        picked_by: user.id
      };

      if (notes) {
        updateData.notes = notes;
      }

      const { data, error } = await supabase
        .from('pick_list_items')
        .update(updateData)
        .eq('id', id)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['pick-list-items'] });
      toast({
        title: "Success",
        description: "Pick item updated successfully",
      });
    },
    onError: (error) => {
      console.error('Error updating pick item:', error);
      toast({
        title: "Error",
        description: "Failed to update pick item",
        variant: "destructive",
      });
    }
  });

  // Fetch Sales Order Items
  const useSalesOrderItems = (salesOrderId: string) => {
    return useQuery({
      queryKey: ['sales-order-items', salesOrderId],
      queryFn: async () => {
        const { data, error } = await supabase
          .from('sales_order_items')
          .select(`
            *,
            finished_goods (
              id,
              product_name,
              product_code,
              current_stock,
              available_stock
            ),
            customer_po_items!cpo_item_id (
              id,
              item_name,
              quantity_ordered
            )
          `)
          .eq('sales_order_id', salesOrderId)
          .order('created_at', { ascending: true });

        if (error) throw error;
        return data;
      },
      enabled: !!salesOrderId
    });
  };

  // Fetch Finished Goods Issues
  const useFinishedGoodsIssues = (salesOrderId?: string) => {
    return useQuery({
      queryKey: ['finished-goods-issues', salesOrderId],
      queryFn: async () => {
        let query = supabase
          .from('finished_goods_issues')
          .select(`
            *,
            sales_orders (
              id,
              order_number,
              customer_id
            )
          `)
          .order('created_at', { ascending: false });

        if (salesOrderId) {
          query = query.eq('sales_order_id', salesOrderId);
        }

        const { data, error } = await query;
        if (error) throw error;
        return data;
      }
    });
  };

  // Fetch Finished Goods Issue Items
  const useFinishedGoodsIssueItems = (issueId: string) => {
    return useQuery({
      queryKey: ['finished-goods-issue-items', issueId],
      queryFn: async () => {
        const { data, error } = await supabase
          .from('finished_goods_issue_items')
          .select(`
            *,
            finished_goods (
              id,
              product_name,
              product_code,
              current_stock
            ),
            sales_order_items (
              id,
              item_name,
              quantity_ordered,
              quantity_issued
            ),
            warehouse_locations!from_location_id (
              id,
              name
            ),
            warehouse_bins!from_bin_id (
              id,
              bin_number
            )
          `)
          .eq('issue_id', issueId)
          .order('created_at', { ascending: true });

        if (error) throw error;
        return data;
      },
      enabled: !!issueId
    });
  };

  // Create Sales Order WITH Items
  const createSalesOrderWithItemsMutation = useMutation({
    mutationFn: async ({ 
      orderData, 
      items 
    }: { 
      orderData: any; 
      items: any[]
    }) => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('Not authenticated');

      // Create sales order
      const { data: salesOrder, error: soError } = await supabase
        .from('sales_orders')
        .insert({
          ...orderData,
          total_items: items.length,
          created_by: user.id
        })
        .select()
        .single();

      if (soError) throw soError;

      // Create sales order items
      const { error: itemsError } = await supabase
        .from('sales_order_items')
        .insert(
          items.map(item => ({
            sales_order_id: salesOrder.id,
            cpo_item_id: item.cpo_item_id,
            finished_good_id: item.finished_good_id,
            item_name: item.item_name,
            description: item.description,
            quantity_ordered: item.quantity_ordered,
            unit_price: item.unit_price,
            total_price: item.total_price,
            company_id: orderData.company_id
          }))
        );

      if (itemsError) throw itemsError;

      return salesOrder;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['sales-orders'] });
      queryClient.invalidateQueries({ queryKey: ['confirmed-cpos'] });
      toast({
        title: "Success",
        description: "Sales order created successfully"
      });
    },
    onError: (error: Error) => {
      toast({
        title: "Error",
        description: `Failed to create sales order: ${error.message}`,
        variant: "destructive"
      });
    }
  });

  // Create Finished Goods Issue
  const createFinishedGoodsIssueMutation = useMutation({
    mutationFn: async ({ 
      issueData, 
      items 
    }: { 
      issueData: any; 
      items: any[]
    }) => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('Not authenticated');

      // Create issue header
      const { data: issue, error: issueError } = await supabase
        .from('finished_goods_issues')
        .insert({
          ...issueData,
          total_items: items.length,
          created_by: user.id
        })
        .select()
        .single();

      if (issueError) throw issueError;

      // Create issue items
      const { error: itemsError } = await supabase
        .from('finished_goods_issue_items')
        .insert(
          items.map((item: any) => ({
            issue_id: issue.id,
            sales_order_item_id: item.sales_order_item_id,
            finished_good_id: item.finished_good_id,
            quantity_to_issue: item.quantity_to_issue,
            quantity_issued: item.quantity_to_issue,
            from_location_id: item.from_location_id,
            from_bin_id: item.from_bin_id,
            batch_number: item.batch_number,
            notes: item.notes,
            status: 'issued'
          }))
        );

      if (itemsError) throw itemsError;

      return issue;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['finished-goods-issues'] });
      queryClient.invalidateQueries({ queryKey: ['sales-order-items'] });
      toast({
        title: "Success",
        description: "Finished goods issue created successfully"
      });
    },
    onError: (error: Error) => {
      toast({
        title: "Error",
        description: `Failed to create issue: ${error.message}`,
        variant: "destructive"
      });
    }
  });

  // Update Issue Status
  const updateIssueStatusMutation = useMutation({
    mutationFn: async ({ issueId, status }: { issueId: string; status: string }) => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('Not authenticated');

      const { error } = await supabase
        .from('finished_goods_issues')
        .update({ 
          status,
          issued_by: status === 'issued' ? user.id : undefined,
          updated_at: new Date().toISOString()
        })
        .eq('id', issueId);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['finished-goods-issues'] });
      queryClient.invalidateQueries({ queryKey: ['sales-order-items'] });
      queryClient.invalidateQueries({ queryKey: ['finished-goods-movements'] });
      toast({
        title: "Success",
        description: "Issue status updated successfully"
      });
    },
    onError: (error: Error) => {
      toast({
        title: "Error",
        description: `Failed to update status: ${error.message}`,
        variant: "destructive"
      });
    }
  });

  return {
    // Queries
    useConfirmedCPOs,
    useSalesOrders,
    usePickLists,
    usePickListItems,
    useSalesOrderItems,
    useFinishedGoodsIssues,
    useFinishedGoodsIssueItems,
    
    // Mutations
    createSalesOrder: createSalesOrderMutation.mutate,
    isCreatingSalesOrder: createSalesOrderMutation.isPending,
    createSalesOrderWithItems: createSalesOrderWithItemsMutation.mutate,
    isCreatingSalesOrderWithItems: createSalesOrderWithItemsMutation.isPending,
    createFinishedGoodsIssue: createFinishedGoodsIssueMutation.mutate,
    isCreatingFinishedGoodsIssue: createFinishedGoodsIssueMutation.isPending,
    updateIssueStatus: updateIssueStatusMutation.mutate,
    isUpdatingIssueStatus: updateIssueStatusMutation.isPending,
    
    createPickList: createPickListMutation.mutate,
    createPickListWithItems: createPickListWithItemsMutation.mutate,
    isCreatingPickList: createPickListMutation.isPending || createPickListWithItemsMutation.isPending,
    
    createPickListItems: createPickListItemsMutation.mutate,
    isCreatingPickListItems: createPickListItemsMutation.isPending,
    
    updatePickListStatus: updatePickListStatusMutation.mutate,
    isUpdatingPickListStatus: updatePickListStatusMutation.isPending,
    
    updatePickListItem: updatePickListItemMutation.mutate,
    isUpdatingPickListItem: updatePickListItemMutation.isPending,
  };
};