import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';
import { 
  SalesOrder, 
  CreateSalesOrderData, 
  PickList, 
  CreatePickListData, 
  PickListItem,
  CreatePickListItemData,
  SalesOrderWithDetails,
  PickListWithDetails 
} from '@/types/pickPack';

export const usePickPack = () => {
  const { toast } = useToast();
  const queryClient = useQueryClient();

  // Fetch confirmed Customer Purchase Orders ready for fulfillment
  const useConfirmedCPOs = () => {
    return useQuery({
      queryKey: ['confirmed-cpos'],
      queryFn: async () => {
        const { data, error } = await supabase
          .from('customer_purchase_orders')
          .select(`
            *,
            customers (
              id,
              customer_name,
              customer_code
            ),
            customer_po_items (
              *,
              finished_goods (
                id,
                product_name,
                product_code,
                current_stock,
                available_stock
              )
            )
          `)
          .eq('status', 'confirmed')
          .order('created_at', { ascending: false });

        if (error) throw error;
        return data || [];
      }
    });
  };

  // Fetch Sales Orders
  const useSalesOrders = () => {
    return useQuery({
      queryKey: ['sales-orders'],
      queryFn: async () => {
        const { data, error } = await supabase
          .from('sales_orders')
          .select(`
            *,
            customer:customers (
              id,
              customer_name,
              customer_code
            ),
            cpo:customer_purchase_orders!cpo_id (
              id,
              cpo_number,
              total_amount
            )
          `)
          .order('created_at', { ascending: false });

        if (error) throw error;
        return data as SalesOrderWithDetails[];
      }
    });
  };

  // Fetch Pick Lists
  const usePickLists = (status?: string) => {
    return useQuery({
      queryKey: ['pick-lists', status],
      queryFn: async () => {
        let query = supabase
          .from('pick_lists')
          .select(`
            *,
            sales_order:sales_orders!sales_order_id (
              id,
              order_number,
              customer_id,
              customer:customers (
                customer_name,
                customer_code
              )
            ),
            picker:profiles!picker_id (
              id,
              full_name
            )
          `)
          .order('created_at', { ascending: false });

        if (status) {
          query = query.eq('status', status);
        }

        const { data, error } = await query;
        if (error) throw error;
        return data as any[];
      }
    });
  };

  // Fetch Pick List Items
  const usePickListItems = (pickListId: string) => {
    return useQuery({
      queryKey: ['pick-list-items', pickListId],
      queryFn: async () => {
        const { data, error } = await supabase
          .from('pick_list_items')
          .select(`
            *,
            finished_goods (
              id,
              product_name,
              product_code,
              current_stock
            ),
            warehouse_locations!location_id (
              id,
              name
            ),
            warehouse_bins!bin_id (
              id,
              bin_number
            )
          `)
          .eq('pick_list_id', pickListId)
          .order('pick_sequence', { ascending: true });

        if (error) throw error;
        return data;
      },
      enabled: !!pickListId
    });
  };

  // Create Sales Order from CPO
  const createSalesOrderMutation = useMutation({
    mutationFn: async (data: CreateSalesOrderData) => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('User not authenticated');

      const { data: salesOrder, error } = await supabase
        .from('sales_orders')
        .insert([{
          ...data,
          order_number: '', // Will be auto-generated by trigger
          created_by: user.id
        }])
        .select()
        .single();

      if (error) throw error;
      return salesOrder;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['sales-orders'] });
      toast({
        title: "Success",
        description: "Sales order created successfully",
      });
    },
    onError: (error) => {
      console.error('Error creating sales order:', error);
      toast({
        title: "Error",
        description: "Failed to create sales order",
        variant: "destructive",
      });
    }
  });

  // Create Pick List
  const createPickListMutation = useMutation({
    mutationFn: async (data: CreatePickListData) => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('User not authenticated');

      const { data: pickList, error } = await supabase
        .from('pick_lists')
        .insert([{
          ...data,
          pick_list_number: '', // Will be auto-generated by trigger
          created_by: user.id
        }])
        .select()
        .single();

      if (error) throw error;
      return pickList;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['pick-lists'] });
      toast({
        title: "Success",
        description: "Pick list created successfully",
      });
    },
    onError: (error) => {
      console.error('Error creating pick list:', error);
      toast({
        title: "Error",
        description: "Failed to create pick list",
        variant: "destructive",
      });
    }
  });

  // Create Pick List Items
  const createPickListItemsMutation = useMutation({
    mutationFn: async (items: CreatePickListItemData[]) => {
      const { data, error } = await supabase
        .from('pick_list_items')
        .insert(items)
        .select();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['pick-list-items'] });
      toast({
        title: "Success",
        description: "Pick list items created successfully",
      });
    },
    onError: (error) => {
      console.error('Error creating pick list items:', error);
      toast({
        title: "Error",
        description: "Failed to create pick list items",
        variant: "destructive",
      });
    }
  });

  // Update Pick List Status
  const updatePickListStatusMutation = useMutation({
    mutationFn: async ({ id, status, pickedBy }: { id: string; status: string; pickedBy?: string }) => {
      const updateData: any = { status };
      
      if (status === 'in_progress') {
        updateData.started_at = new Date().toISOString();
      } else if (status === 'completed') {
        updateData.completed_at = new Date().toISOString();
      }

      if (pickedBy) {
        updateData.picker_id = pickedBy;
      }

      const { data, error } = await supabase
        .from('pick_lists')
        .update(updateData)
        .eq('id', id)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['pick-lists'] });
      toast({
        title: "Success",
        description: "Pick list status updated successfully",
      });
    },
    onError: (error) => {
      console.error('Error updating pick list status:', error);
      toast({
        title: "Error",
        description: "Failed to update pick list status",
        variant: "destructive",
      });
    }
  });

  // Update Pick List Item
  const updatePickListItemMutation = useMutation({
    mutationFn: async ({ 
      id, 
      quantityPicked, 
      status, 
      notes 
    }: { 
      id: string; 
      quantityPicked: number; 
      status: string; 
      notes?: string 
    }) => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('User not authenticated');

      const updateData: any = {
        quantity_picked: quantityPicked,
        status,
        picked_at: new Date().toISOString(),
        picked_by: user.id
      };

      if (notes) {
        updateData.notes = notes;
      }

      const { data, error } = await supabase
        .from('pick_list_items')
        .update(updateData)
        .eq('id', id)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['pick-list-items'] });
      toast({
        title: "Success",
        description: "Pick item updated successfully",
      });
    },
    onError: (error) => {
      console.error('Error updating pick item:', error);
      toast({
        title: "Error",
        description: "Failed to update pick item",
        variant: "destructive",
      });
    }
  });

  return {
    // Queries
    useConfirmedCPOs,
    useSalesOrders,
    usePickLists,
    usePickListItems,
    
    // Mutations
    createSalesOrder: createSalesOrderMutation.mutate,
    isCreatingSalesOrder: createSalesOrderMutation.isPending,
    
    createPickList: createPickListMutation.mutate,
    isCreatingPickList: createPickListMutation.isPending,
    
    createPickListItems: createPickListItemsMutation.mutate,
    isCreatingPickListItems: createPickListItemsMutation.isPending,
    
    updatePickListStatus: updatePickListStatusMutation.mutate,
    isUpdatingPickListStatus: updatePickListStatusMutation.isPending,
    
    updatePickListItem: updatePickListItemMutation.mutate,
    isUpdatingPickListItem: updatePickListItemMutation.isPending,
  };
};