import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { getCachedUser } from "@/lib/currentUser";
import { useToast } from "@/hooks/use-toast";
import type { RfqRfpRequest, CreateRfqRfpData, SupplierQuote, CreateQuoteData } from "@/types/rfqRfp";

// Fetch all RFQ/RFP requests
export function useRfqRfpRequests(companyId?: string) {
  return useQuery({
    queryKey: ["rfq-rfp-requests", companyId],
    queryFn: async () => {
      let query = supabase
        .from("rfq_rfp_requests")
        .select(`
          *,
          items:rfq_rfp_items(*),
          invited_suppliers:rfq_rfp_invited_suppliers(
            *,
            supplier:suppliers(id, name, email, phone)
          ),
          quotes:supplier_quotes(
            *,
            supplier:suppliers(id, name, supplier_code)
          )
        `)
        .order("created_at", { ascending: false });

      if (companyId) {
        query = query.eq("company_id", companyId);
      }

      const { data, error } = await query;

      if (error) throw error;
      return data as RfqRfpRequest[];
    },
    enabled: !!companyId,
  });
}

// Fetch single RFQ/RFP request
export function useRfqRfpRequest(id?: string) {
  return useQuery({
    queryKey: ["rfq-rfp-request", id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("rfq_rfp_requests")
        .select(`
          *,
          items:rfq_rfp_items(*),
          invited_suppliers:rfq_rfp_invited_suppliers(
            *,
            supplier:suppliers(id, name, email, phone)
          ),
          quotes:supplier_quotes(
            *,
            items:supplier_quote_items(*),
            supplier:suppliers(id, name, supplier_code)
          )
        `)
        .eq("id", id!)
        .single();

      if (error) throw error;
      return data as RfqRfpRequest;
    },
    enabled: !!id,
  });
}

// Create RFQ/RFP request
export function useCreateRfqRfpRequest() {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async (data: CreateRfqRfpData) => {
      const { items, invited_supplier_ids, ...requestData } = data;

      // Get current user
      const user = getCachedUser();
      if (!user) throw new Error("Not authenticated");

      // Create the request
      const { data: request, error: requestError } = await supabase
        .from("rfq_rfp_requests")
        .insert([{
          ...requestData,
          request_number: '', // Will be auto-generated by trigger
          created_by: user.id,
        }])
        .select()
        .single();

      if (requestError) throw requestError;

      // Create items
      if (items.length > 0) {
        const itemsToInsert = items.map((item, index) => ({
          ...item,
          request_id: request.id,
          line_number: index + 1,
        }));

        const { error: itemsError } = await supabase
          .from("rfq_rfp_items")
          .insert(itemsToInsert);

        if (itemsError) throw itemsError;
      }

      // Invite suppliers
      if (invited_supplier_ids && invited_supplier_ids.length > 0) {
        const invitations = invited_supplier_ids.map(supplier_id => ({
          request_id: request.id,
          supplier_id,
        }));

        const { error: invitationsError } = await supabase
          .from("rfq_rfp_invited_suppliers")
          .insert(invitations);

        if (invitationsError) throw invitationsError;
      }

      return request;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["rfq-rfp-requests"] });
      toast({
        title: "Success",
        description: "RFQ/RFP request created successfully",
      });
    },
    onError: (error: Error) => {
      toast({
        title: "Error",
        description: error.message,
        variant: "destructive",
      });
    },
  });
}

// Update RFQ/RFP request
export function useUpdateRfqRfpRequest() {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async ({ id, ...data }: Partial<RfqRfpRequest> & { id: string }) => {
      const { data: updated, error } = await supabase
        .from("rfq_rfp_requests")
        .update(data)
        .eq("id", id)
        .select()
        .single();

      if (error) throw error;
      return updated;
    },
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ["rfq-rfp-requests"] });
      queryClient.invalidateQueries({ queryKey: ["rfq-rfp-request", variables.id] });
      toast({
        title: "Success",
        description: "RFQ/RFP request updated successfully",
      });
    },
    onError: (error: Error) => {
      toast({
        title: "Error",
        description: error.message,
        variant: "destructive",
      });
    },
  });
}

// Publish RFQ/RFP request
export function usePublishRfqRfpRequest() {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async (id: string) => {
      const { data: updated, error } = await supabase
        .from("rfq_rfp_requests")
        .update({ status: 'published' })
        .eq("id", id)
        .select()
        .single();

      if (error) throw error;
      return updated;
    },
    onSuccess: (_, id) => {
      queryClient.invalidateQueries({ queryKey: ["rfq-rfp-requests"] });
      queryClient.invalidateQueries({ queryKey: ["rfq-rfp-request", id] });
      toast({
        title: "Success",
        description: "RFQ/RFP request published successfully",
      });
    },
    onError: (error: Error) => {
      toast({
        title: "Error",
        description: error.message,
        variant: "destructive",
      });
    },
  });
}

// Fetch quotes for a request
export function useSupplierQuotes(requestId?: string) {
  return useQuery({
    queryKey: ["supplier-quotes", requestId],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("supplier_quotes")
        .select(`
          *,
          items:supplier_quote_items(*),
          supplier:suppliers(id, name, supplier_code)
        `)
        .eq("request_id", requestId!)
        .order("submission_date", { ascending: false });

      if (error) throw error;
      return data as SupplierQuote[];
    },
    enabled: !!requestId,
  });
}

// Create supplier quote
export function useCreateSupplierQuote() {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async (data: CreateQuoteData) => {
      const { items, ...quoteData } = data;

      // Get current user
      const user = getCachedUser();
      if (!user) throw new Error("Not authenticated");

      // Create the quote
      const { data: quote, error: quoteError } = await supabase
        .from("supplier_quotes")
        .insert([{
          ...quoteData,
          quote_number: '', // Will be auto-generated by trigger
          created_by: user.id,
        }])
        .select()
        .single();

      if (quoteError) throw quoteError;

      // Create quote items
      if (items.length > 0) {
        const itemsToInsert = items.map((item, index) => ({
          ...item,
          quote_id: quote.id,
          line_number: index + 1,
        }));

        const { error: itemsError } = await supabase
          .from("supplier_quote_items")
          .insert(itemsToInsert);

        if (itemsError) throw itemsError;
      }

      return quote;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ["supplier-quotes", data.request_id] });
      queryClient.invalidateQueries({ queryKey: ["rfq-rfp-request", data.request_id] });
      toast({
        title: "Success",
        description: "Quote submitted successfully",
      });
    },
    onError: (error: Error) => {
      toast({
        title: "Error",
        description: error.message,
        variant: "destructive",
      });
    },
  });
}

// Update supplier quote
export function useUpdateSupplierQuote() {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async ({ id, ...data }: Partial<SupplierQuote> & { id: string }) => {
      const { data: updated, error } = await supabase
        .from("supplier_quotes")
        .update(data)
        .eq("id", id)
        .select()
        .single();

      if (error) throw error;
      return updated;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ["supplier-quotes", data.request_id] });
      queryClient.invalidateQueries({ queryKey: ["rfq-rfp-request", data.request_id] });
      toast({
        title: "Success",
        description: "Quote updated successfully",
      });
    },
    onError: (error: Error) => {
      toast({
        title: "Error",
        description: error.message,
        variant: "destructive",
      });
    },
  });
}
