import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import type { 
  StockTransferRequest, 
  StockTransferItem,
  CreateStockTransferData,
  CreateStockTransferItemData,
  TransferStatus
} from "@/types/stockTransfer";

export const useStockTransferRequests = (status?: TransferStatus) => {
  return useQuery({
    queryKey: ["stock-transfer-requests", status],
    queryFn: async () => {
      let query = supabase
        .from("stock_transfer_requests")
        .select("*")
        .order("created_at", { ascending: false });

      if (status) {
        query = query.eq("status", status);
      }

      const { data, error } = await query;
      if (error) throw error;
      return data as StockTransferRequest[];
    },
  });
};

export const useStockTransferItems = (transferId: string | undefined) => {
  return useQuery({
    queryKey: ["stock-transfer-items", transferId],
    queryFn: async () => {
      if (!transferId) return [];
      
      const { data, error } = await supabase
        .from("stock_transfer_items")
        .select("*")
        .eq("transfer_id", transferId)
        .order("created_at", { ascending: true });

      if (error) throw error;
      return data as StockTransferItem[];
    },
    enabled: !!transferId,
  });
};

export const useCreateStockTransfer = () => {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async (data: CreateStockTransferData) => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error("User not authenticated");

      const { data: transfer, error } = await supabase
        .from("stock_transfer_requests")
        .insert({
          ...data,
          transfer_number: '', // Auto-generated by trigger
          created_by: user.id,
          requested_by: user.id,
          // Auto-set approval info if status is 'approved' (skip approval workflow)
          ...(data.status === 'approved' && {
            approved_by: user.id,
            approved_date: new Date().toISOString(),
          }),
        })
        .select()
        .single();

      if (error) throw error;
      return transfer as StockTransferRequest;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["stock-transfer-requests"] });
      toast({
        title: "Transfer Created",
        description: "Stock transfer request created successfully.",
      });
    },
    onError: (error) => {
      console.error("Create transfer error:", error);
      toast({
        title: "Error",
        description: "Failed to create transfer request.",
        variant: "destructive",
      });
    },
  });
};

export const useCreateStockTransferItem = () => {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async (data: CreateStockTransferItemData) => {
      const { data: item, error } = await supabase
        .from("stock_transfer_items")
        .insert(data)
        .select()
        .single();

      if (error) throw error;
      return item as StockTransferItem;
    },
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ["stock-transfer-items", variables.transfer_id] });
    },
    onError: (error) => {
      console.error("Create transfer item error:", error);
      toast({
        title: "Error",
        description: "Failed to add item to transfer.",
        variant: "destructive",
      });
    },
  });
};

export const useUpdateStockTransfer = () => {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async ({ id, data }: { id: string; data: Partial<StockTransferRequest> }) => {
      const { error } = await supabase
        .from("stock_transfer_requests")
        .update(data)
        .eq("id", id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["stock-transfer-requests"] });
      toast({
        title: "Transfer Updated",
        description: "Stock transfer request updated successfully.",
      });
    },
    onError: (error) => {
      console.error("Update transfer error:", error);
      toast({
        title: "Error",
        description: "Failed to update transfer request.",
        variant: "destructive",
      });
    },
  });
};

export const useApproveStockTransfer = () => {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async (transferId: string) => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error("User not authenticated");

      const { error } = await supabase
        .from("stock_transfer_requests")
        .update({
          status: 'approved',
          approved_by: user.id,
          approved_date: new Date().toISOString(),
        })
        .eq("id", transferId);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["stock-transfer-requests"] });
      toast({
        title: "Transfer Approved",
        description: "Stock transfer request has been approved.",
      });
    },
    onError: (error) => {
      console.error("Approve transfer error:", error);
      toast({
        title: "Error",
        description: "Failed to approve transfer request.",
        variant: "destructive",
      });
    },
  });
};

export const useCompleteStockTransfer = () => {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async (transferId: string) => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error("User not authenticated");

      // Get transfer items
      const { data: items, error: itemsError } = await supabase
        .from("stock_transfer_items")
        .select("*")
        .eq("transfer_id", transferId);

      if (itemsError) throw itemsError;
      if (!items || items.length === 0) throw new Error("No items in transfer");

      // Get transfer details
      const { data: transfer, error: transferError } = await supabase
        .from("stock_transfer_requests")
        .select("*")
        .eq("id", transferId)
        .single();

      if (transferError) throw transferError;

      const fromLocationId = transfer.from_location_id;
      const toLocationId = transfer.to_location_id;

      // Process each item
      for (const item of items) {
        // Get current stock for transaction records
        const { data: warehouseItem } = await supabase
          .from("warehouse_items")
          .select("current_stock")
          .eq("id", item.warehouse_item_id)
          .single();

        const currentStock = warehouseItem?.current_stock || 0;

        // Create transfer out transaction
        await supabase.from("stock_transactions").insert({
          item_id: item.warehouse_item_id,
          transaction_type: 'transfer_out',
          reference_type: 'transfer',
          reference_id: transferId,
          quantity_change: -item.quantity_requested,
          quantity_before: currentStock,
          quantity_after: currentStock - item.quantity_requested,
          notes: `Transfer ${transfer.transfer_number} - Out from ${fromLocationId}`,
          created_by: user.id,
        });

        // Create transfer in transaction
        await supabase.from("stock_transactions").insert({
          item_id: item.warehouse_item_id,
          transaction_type: 'transfer_in',
          reference_type: 'transfer',
          reference_id: transferId,
          quantity_change: item.quantity_requested,
          quantity_before: currentStock - item.quantity_requested,
          quantity_after: currentStock,
          notes: `Transfer ${transfer.transfer_number} - In to ${toLocationId}`,
          created_by: user.id,
        });

        // Update item status
        await supabase
          .from("stock_transfer_items")
          .update({
            status: 'completed',
            quantity_transferred: item.quantity_requested,
          })
          .eq("id", item.id);

        // ===== UPDATE SOURCE BIN ALLOCATION (decrease stock) =====
        // Two-step approach: First get bin IDs at from_location, then filter allocations
        const { data: fromBins, error: fromBinsError } = await supabase
          .from('warehouse_bins')
          .select('id')
          .eq('location_id', fromLocationId);

        if (fromBinsError) {
          console.error('Failed to get source bins:', fromBinsError);
          throw fromBinsError;
        }

        if (fromBins && fromBins.length > 0) {
          const fromBinIds = fromBins.map(b => b.id);
          
          // Get allocations for this item in those bins
          const { data: sourceAllocations, error: sourceAllocError } = await supabase
            .from('warehouse_bin_allocations')
            .select('*')
            .eq('warehouse_item_id', item.warehouse_item_id)
            .in('bin_id', fromBinIds);

          if (sourceAllocError) {
            console.error('Failed to get source allocations:', sourceAllocError);
            throw sourceAllocError;
          }

          console.log('Source allocations found:', sourceAllocations);

          if (sourceAllocations && sourceAllocations.length > 0) {
            const sourceAlloc = sourceAllocations[0];
            const newAllocated = Math.max(0, (sourceAlloc.allocated_quantity || 0) - item.quantity_requested);
            const newAvailable = Math.max(0, (sourceAlloc.available_quantity || 0) - item.quantity_requested);

            console.log('Updating source allocation:', {
              id: sourceAlloc.id,
              oldAllocated: sourceAlloc.allocated_quantity,
              oldAvailable: sourceAlloc.available_quantity,
              newAllocated,
              newAvailable,
              quantityTransferred: item.quantity_requested,
            });

            const { error: updateSourceError } = await supabase
              .from('warehouse_bin_allocations')
              .update({
                allocated_quantity: newAllocated,
                available_quantity: newAvailable,
              })
              .eq('id', sourceAlloc.id);

            if (updateSourceError) {
              console.error('Failed to update source allocation:', updateSourceError);
              throw updateSourceError;
            }

            // Also update the source bin's current_quantity
            const { data: sourceBinData, error: sourceBinFetchError } = await supabase
              .from("warehouse_bins")
              .select("current_quantity")
              .eq("id", sourceAlloc.bin_id)
              .single();

            if (sourceBinFetchError) {
              console.error('Failed to get source bin data:', sourceBinFetchError);
            } else if (sourceBinData) {
              const { error: updateSourceBinError } = await supabase
                .from("warehouse_bins")
                .update({
                  current_quantity: Math.max(0, (sourceBinData.current_quantity || 0) - item.quantity_requested),
                })
                .eq("id", sourceAlloc.bin_id);

              if (updateSourceBinError) {
                console.error('Failed to update source bin quantity:', updateSourceBinError);
              }
            }
          } else {
            console.warn('No source allocations found for item:', item.warehouse_item_id, 'at location:', fromLocationId);
          }
        } else {
          console.warn('No bins found at source location:', fromLocationId);
        }

        // ===== CREATE OR UPDATE DESTINATION BIN ALLOCATION (increase stock) =====
        // First, find a bin at the destination location
        const { data: destBins, error: destBinsError } = await supabase
          .from('warehouse_bins')
          .select('id')
          .eq('location_id', toLocationId)
          .limit(1);

        if (destBinsError) {
          console.error('Failed to get destination bins:', destBinsError);
          throw destBinsError;
        }

        if (destBins && destBins.length > 0) {
          const destBinId = destBins[0].id;

          // Check if allocation already exists at destination
          const { data: destAllocation, error: destAllocError } = await supabase
            .from('warehouse_bin_allocations')
            .select('*')
            .eq('warehouse_item_id', item.warehouse_item_id)
            .eq('bin_id', destBinId)
            .maybeSingle();

          if (destAllocError) {
            console.error('Failed to check destination allocation:', destAllocError);
            throw destAllocError;
          }

          if (destAllocation) {
            // Update existing allocation
            const newAllocated = (destAllocation.allocated_quantity || 0) + item.quantity_requested;
            const newAvailable = (destAllocation.available_quantity || 0) + item.quantity_requested;

            console.log('Updating destination allocation:', {
              id: destAllocation.id,
              oldAllocated: destAllocation.allocated_quantity,
              oldAvailable: destAllocation.available_quantity,
              newAllocated,
              newAvailable,
            });

            const { error: updateDestError } = await supabase
              .from('warehouse_bin_allocations')
              .update({
                allocated_quantity: newAllocated,
                available_quantity: newAvailable,
              })
              .eq('id', destAllocation.id);

            if (updateDestError) {
              console.error('Failed to update destination allocation:', updateDestError);
              throw updateDestError;
            }
          } else {
            // Create new allocation at destination
            console.log('Creating new destination allocation:', {
              warehouse_item_id: item.warehouse_item_id,
              bin_id: destBinId,
              quantity: item.quantity_requested,
            });

            const { error: insertDestError } = await supabase
              .from('warehouse_bin_allocations')
              .insert({
                warehouse_item_id: item.warehouse_item_id,
                bin_id: destBinId,
                allocated_quantity: item.quantity_requested,
                available_quantity: item.quantity_requested,
                reserved_quantity: 0,
              });

            if (insertDestError) {
              console.error('Failed to create destination allocation:', insertDestError);
              throw insertDestError;
            }
          }

          // Update destination bin's current_quantity
          const { data: destBinData, error: destBinFetchError } = await supabase
            .from("warehouse_bins")
            .select("current_quantity")
            .eq("id", destBinId)
            .single();

          if (destBinFetchError) {
            console.error('Failed to get destination bin data:', destBinFetchError);
          } else if (destBinData) {
            const { error: updateDestBinError } = await supabase
              .from("warehouse_bins")
              .update({
                current_quantity: (destBinData.current_quantity || 0) + item.quantity_requested,
              })
              .eq("id", destBinId);

            if (updateDestBinError) {
              console.error('Failed to update destination bin quantity:', updateDestBinError);
            }
          }
        } else {
          console.warn('No bins found at destination location:', toLocationId);
        }

        // Also update bin current_quantity if bins specified (for backward compatibility)
        if (item.from_bin_id) {
          const { data: fromBin } = await supabase
            .from("warehouse_bins")
            .select("current_quantity")
            .eq("id", item.from_bin_id)
            .single();

          if (fromBin) {
            await supabase
              .from("warehouse_bins")
              .update({
                current_quantity: Math.max(0, (fromBin.current_quantity || 0) - item.quantity_requested),
              })
              .eq("id", item.from_bin_id);
          }
        }

        if (item.to_bin_id) {
          const { data: toBin } = await supabase
            .from("warehouse_bins")
            .select("current_quantity")
            .eq("id", item.to_bin_id)
            .single();

          if (toBin) {
            await supabase
              .from("warehouse_bins")
              .update({
                current_quantity: (toBin.current_quantity || 0) + item.quantity_requested,
              })
              .eq("id", item.to_bin_id);
          }
        }
      }

      // Update transfer status
      const { error: updateError } = await supabase
        .from("stock_transfer_requests")
        .update({
          status: 'completed',
          completed_by: user.id,
          completed_date: new Date().toISOString(),
        })
        .eq("id", transferId);

      if (updateError) throw updateError;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["stock-transfer-requests"] });
      queryClient.invalidateQueries({ queryKey: ["stock-transfer-items"] });
      queryClient.invalidateQueries({ queryKey: ["warehouse-items"] });
      queryClient.invalidateQueries({ queryKey: ["warehouse-bins"] });
      queryClient.invalidateQueries({ queryKey: ["all-items-location-stock"] });
      queryClient.invalidateQueries({ queryKey: ["item-bin-allocations-for-transfer"] });
      queryClient.invalidateQueries({ queryKey: ["warehouse-bin-allocations"] });
      toast({
        title: "Transfer Completed",
        description: "Stock transfer has been completed successfully.",
      });
    },
    onError: (error) => {
      console.error("Complete transfer error:", error);
      toast({
        title: "Error",
        description: "Failed to complete transfer.",
        variant: "destructive",
      });
    },
  });
};

export const useDeleteStockTransfer = () => {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async (transferId: string) => {
      const { error } = await supabase
        .from("stock_transfer_requests")
        .delete()
        .eq("id", transferId);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["stock-transfer-requests"] });
      toast({
        title: "Transfer Deleted",
        description: "Stock transfer request has been deleted.",
      });
    },
    onError: (error) => {
      console.error("Delete transfer error:", error);
      toast({
        title: "Error",
        description: "Failed to delete transfer request.",
        variant: "destructive",
      });
    },
  });
};
