import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import type { 
  StockTransferRequest, 
  StockTransferItem,
  CreateStockTransferData,
  CreateStockTransferItemData,
  TransferStatus
} from "@/types/stockTransfer";

export const useStockTransferRequests = (status?: TransferStatus) => {
  return useQuery({
    queryKey: ["stock-transfer-requests", status],
    queryFn: async () => {
      let query = supabase
        .from("stock_transfer_requests")
        .select("*")
        .order("created_at", { ascending: false });

      if (status) {
        query = query.eq("status", status);
      }

      const { data, error } = await query;
      if (error) throw error;
      return data as StockTransferRequest[];
    },
  });
};

export const useStockTransferItems = (transferId: string | undefined) => {
  return useQuery({
    queryKey: ["stock-transfer-items", transferId],
    queryFn: async () => {
      if (!transferId) return [];
      
      const { data, error } = await supabase
        .from("stock_transfer_items")
        .select("*")
        .eq("transfer_id", transferId)
        .order("created_at", { ascending: true });

      if (error) throw error;
      return data as StockTransferItem[];
    },
    enabled: !!transferId,
  });
};

export const useCreateStockTransfer = () => {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async (data: CreateStockTransferData) => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error("User not authenticated");

      const { data: transfer, error } = await supabase
        .from("stock_transfer_requests")
        .insert({
          ...data,
          transfer_number: '', // Auto-generated by trigger
          created_by: user.id,
          requested_by: user.id,
          // Auto-set approval info if status is 'approved' (skip approval workflow)
          ...(data.status === 'approved' && {
            approved_by: user.id,
            approved_date: new Date().toISOString(),
          }),
        })
        .select()
        .single();

      if (error) throw error;
      return transfer as StockTransferRequest;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["stock-transfer-requests"] });
      toast({
        title: "Transfer Created",
        description: "Stock transfer request created successfully.",
      });
    },
    onError: (error) => {
      console.error("Create transfer error:", error);
      toast({
        title: "Error",
        description: "Failed to create transfer request.",
        variant: "destructive",
      });
    },
  });
};

export const useCreateStockTransferItem = () => {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async (data: CreateStockTransferItemData) => {
      const { data: item, error } = await supabase
        .from("stock_transfer_items")
        .insert(data)
        .select()
        .single();

      if (error) throw error;
      return item as StockTransferItem;
    },
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ["stock-transfer-items", variables.transfer_id] });
    },
    onError: (error) => {
      console.error("Create transfer item error:", error);
      toast({
        title: "Error",
        description: "Failed to add item to transfer.",
        variant: "destructive",
      });
    },
  });
};

export const useUpdateStockTransfer = () => {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async ({ id, data }: { id: string; data: Partial<StockTransferRequest> }) => {
      const { error } = await supabase
        .from("stock_transfer_requests")
        .update(data)
        .eq("id", id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["stock-transfer-requests"] });
      toast({
        title: "Transfer Updated",
        description: "Stock transfer request updated successfully.",
      });
    },
    onError: (error) => {
      console.error("Update transfer error:", error);
      toast({
        title: "Error",
        description: "Failed to update transfer request.",
        variant: "destructive",
      });
    },
  });
};

export const useApproveStockTransfer = () => {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async (transferId: string) => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error("User not authenticated");

      const { error } = await supabase
        .from("stock_transfer_requests")
        .update({
          status: 'approved',
          approved_by: user.id,
          approved_date: new Date().toISOString(),
        })
        .eq("id", transferId);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["stock-transfer-requests"] });
      toast({
        title: "Transfer Approved",
        description: "Stock transfer request has been approved.",
      });
    },
    onError: (error) => {
      console.error("Approve transfer error:", error);
      toast({
        title: "Error",
        description: "Failed to approve transfer request.",
        variant: "destructive",
      });
    },
  });
};

export const useCompleteStockTransfer = () => {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async (transferId: string) => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error("User not authenticated");

      // Get transfer items
      const { data: items, error: itemsError } = await supabase
        .from("stock_transfer_items")
        .select("*")
        .eq("transfer_id", transferId);

      if (itemsError) throw itemsError;
      if (!items || items.length === 0) throw new Error("No items in transfer");

      // Get transfer details
      const { data: transfer, error: transferError } = await supabase
        .from("stock_transfer_requests")
        .select("*")
        .eq("id", transferId)
        .single();

      if (transferError) throw transferError;

      // Process each item
      for (const item of items) {
        // Get current stock
        const { data: warehouseItem } = await supabase
          .from("warehouse_items")
          .select("current_stock")
          .eq("id", item.warehouse_item_id)
          .single();

        const currentStock = warehouseItem?.current_stock || 0;

        // Create transfer out transaction
        await supabase.from("stock_transactions").insert({
          item_id: item.warehouse_item_id,
          transaction_type: 'transfer_out',
          reference_type: 'transfer',
          reference_id: transferId,
          quantity_change: -item.quantity_requested,
          quantity_before: currentStock,
          quantity_after: currentStock - item.quantity_requested,
          notes: `Transfer ${transfer.transfer_number} - Out`,
          created_by: user.id,
        });

        // Create transfer in transaction
        await supabase.from("stock_transactions").insert({
          item_id: item.warehouse_item_id,
          transaction_type: 'transfer_in',
          reference_type: 'transfer',
          reference_id: transferId,
          quantity_change: item.quantity_requested,
          quantity_before: currentStock - item.quantity_requested,
          quantity_after: currentStock,
          notes: `Transfer ${transfer.transfer_number} - In`,
          created_by: user.id,
        });

        // Update item status
        await supabase
          .from("stock_transfer_items")
          .update({
            status: 'completed',
            quantity_transferred: item.quantity_requested,
          })
          .eq("id", item.id);

        // Update bin quantities if bins specified
        if (item.from_bin_id) {
          const { data: fromBin } = await supabase
            .from("warehouse_bins")
            .select("current_quantity")
            .eq("id", item.from_bin_id)
            .single();

          if (fromBin) {
            await supabase
              .from("warehouse_bins")
              .update({
                current_quantity: (fromBin.current_quantity || 0) - item.quantity_requested,
              })
              .eq("id", item.from_bin_id);
          }
        }

        if (item.to_bin_id) {
          const { data: toBin } = await supabase
            .from("warehouse_bins")
            .select("current_quantity")
            .eq("id", item.to_bin_id)
            .single();

          if (toBin) {
            await supabase
              .from("warehouse_bins")
              .update({
                current_quantity: (toBin.current_quantity || 0) + item.quantity_requested,
              })
              .eq("id", item.to_bin_id);
          }
        }
      }

      // Update transfer status
      const { error: updateError } = await supabase
        .from("stock_transfer_requests")
        .update({
          status: 'completed',
          completed_by: user.id,
          completed_date: new Date().toISOString(),
        })
        .eq("id", transferId);

      if (updateError) throw updateError;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["stock-transfer-requests"] });
      queryClient.invalidateQueries({ queryKey: ["stock-transfer-items"] });
      queryClient.invalidateQueries({ queryKey: ["warehouse-items"] });
      queryClient.invalidateQueries({ queryKey: ["warehouse-bins"] });
      toast({
        title: "Transfer Completed",
        description: "Stock transfer has been completed successfully.",
      });
    },
    onError: (error) => {
      console.error("Complete transfer error:", error);
      toast({
        title: "Error",
        description: "Failed to complete transfer.",
        variant: "destructive",
      });
    },
  });
};

export const useDeleteStockTransfer = () => {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: async (transferId: string) => {
      const { error } = await supabase
        .from("stock_transfer_requests")
        .delete()
        .eq("id", transferId);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["stock-transfer-requests"] });
      toast({
        title: "Transfer Deleted",
        description: "Stock transfer request has been deleted.",
      });
    },
    onError: (error) => {
      console.error("Delete transfer error:", error);
      toast({
        title: "Error",
        description: "Failed to delete transfer request.",
        variant: "destructive",
      });
    },
  });
};
