import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { flattenWarehouseItem } from '@/lib/flattenWarehouseItem';
import { supabase } from "@/integrations/supabase/client";
import { toast } from "@/hooks/use-toast";
import {
  SupplierEvaluation,
  SupplierEvaluationEntry,
  CreateSupplierEvaluationData,
  CreateSupplierEvaluationEntryData,
} from "@/types/supplierEvaluation";
import { useUpdateSupplierRating } from "./useSupplierRatings";

// Fetch all supplier evaluations
export const useSupplierEvaluations = () => {
  return useQuery({
    queryKey: ["supplier-evaluations"],
    queryFn: async (): Promise<SupplierEvaluation[]> => {
      const { data, error } = await supabase
        .from("supplier_evaluations")
        .select(`
          *,
          supplier:suppliers(id, name, supplier_code),
          warehouse_item:warehouse_items(
            id,
            catalog:warehouse_item_catalog!warehouse_items_catalog_item_id_fkey(item_code, name)
          )
        `)
        .order("created_at", { ascending: false });

      if (error) throw error;
      return ((data || []) as any[]).map(flattenWarehouseItem) as SupplierEvaluation[];
    },
  });
};

// Fetch single supplier evaluation with entries
export const useSupplierEvaluation = (id: string) => {
  return useQuery({
    queryKey: ["supplier-evaluation", id],
    queryFn: async (): Promise<SupplierEvaluation | null> => {
      const { data, error } = await supabase
        .from("supplier_evaluations")
        .select(`
          *,
          supplier:suppliers(id, name, supplier_code),
          warehouse_item:warehouse_items(
            id,
            catalog:warehouse_item_catalog!warehouse_items_catalog_item_id_fkey(item_code, name)
          ),
          entries:supplier_evaluation_entries(
            *,
            warehouse_item:warehouse_items(
            id,
            catalog:warehouse_item_catalog!warehouse_items_catalog_item_id_fkey(item_code, name)
          )
          )
        `)
        .eq("id", id)
        .maybeSingle();

      if (error) throw error;
      return data;
    },
    enabled: !!id,
  });
};

// Create supplier evaluation
export const useCreateSupplierEvaluation = () => {
  const queryClient = useQueryClient();
  const updateRating = useUpdateSupplierRating();

  return useMutation({
    mutationFn: async (data: CreateSupplierEvaluationData): Promise<SupplierEvaluation> => {
      const { data: user } = await supabase.auth.getUser();
      if (!user?.user?.id) throw new Error("User not authenticated");

      const evaluationData = {
        ...data,
        evaluation_number: '', // Will be auto-generated by trigger
        created_by: user.user.id,
        evaluated_by: user.user.id,
      };

      // Remove evaluation_number since it's auto-generated by trigger
      const { data: evaluation, error } = await supabase
        .from("supplier_evaluations")
        .insert(evaluationData)
        .select(`
          *,
          supplier:suppliers(id, name, supplier_code),
          warehouse_item:warehouse_items(
            id,
            catalog:warehouse_item_catalog!warehouse_items_catalog_item_id_fkey(item_code, name)
          )
        `)
        .single();

      if (error) throw error;
      return evaluation;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ["supplier-evaluations"] });
      // Update supplier rating based on new evaluation
      updateRating.mutate(data.supplier_id);
      toast({
        title: "Success",
        description: "Supplier evaluation created successfully",
      });
    },
    onError: (error: Error) => {
      toast({
        title: "Error",
        description: `Failed to create evaluation: ${error.message}`,
        variant: "destructive",
      });
    },
  });
};

// Update supplier evaluation
export const useUpdateSupplierEvaluation = () => {
  const queryClient = useQueryClient();
  const updateRating = useUpdateSupplierRating();

  return useMutation({
    mutationFn: async ({ 
      id, 
      updates 
    }: { 
      id: string; 
      updates: Partial<CreateSupplierEvaluationData & { status: string }> 
    }): Promise<SupplierEvaluation> => {
      const { data, error } = await supabase
        .from("supplier_evaluations")
        .update(updates)
        .eq("id", id)
        .select(`
          *,
          supplier:suppliers(id, name, supplier_code),
          warehouse_item:warehouse_items(
            id,
            catalog:warehouse_item_catalog!warehouse_items_catalog_item_id_fkey(item_code, name)
          )
        `)
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ["supplier-evaluations"] });
      queryClient.invalidateQueries({ queryKey: ["supplier-evaluation", data.id] });
      // Update supplier rating based on updated evaluation
      updateRating.mutate(data.supplier_id);
      toast({
        title: "Success",
        description: "Supplier evaluation updated successfully",
      });
    },
    onError: (error: Error) => {
      toast({
        title: "Error",
        description: `Failed to update evaluation: ${error.message}`,
        variant: "destructive",
      });
    },
  });
};

// Delete supplier evaluation
export const useDeleteSupplierEvaluation = () => {
  const queryClient = useQueryClient();
  const updateRating = useUpdateSupplierRating();

  return useMutation({
    mutationFn: async ({ id, supplierId }: { id: string; supplierId: string }): Promise<string> => {
      const { error } = await supabase
        .from("supplier_evaluations")
        .delete()
        .eq("id", id);

      if (error) throw error;
      return supplierId;
    },
    onSuccess: (supplierId) => {
      queryClient.invalidateQueries({ queryKey: ["supplier-evaluations"] });
      // Update supplier rating after evaluation deletion
      updateRating.mutate(supplierId);
      toast({
        title: "Success",
        description: "Supplier evaluation deleted successfully",
      });
    },
    onError: (error: Error) => {
      toast({
        title: "Error",
        description: `Failed to delete evaluation: ${error.message}`,
        variant: "destructive",
      });
    },
  });
};

// Fetch evaluation entries for a specific evaluation
export const useSupplierEvaluationEntries = (evaluationId: string) => {
  return useQuery({
    queryKey: ["supplier-evaluation-entries", evaluationId],
    queryFn: async (): Promise<SupplierEvaluationEntry[]> => {
      const { data, error } = await supabase
        .from("supplier_evaluation_entries")
        .select(`
          *,
          warehouse_item:warehouse_items(
            id,
            catalog:warehouse_item_catalog!warehouse_items_catalog_item_id_fkey(item_code, name)
          )
        `)
        .eq("evaluation_id", evaluationId)
        .order("receipt_date", { ascending: false });

      if (error) throw error;
      return data || [];
    },
    enabled: !!evaluationId,
  });
};

// Create evaluation entry
export const useCreateSupplierEvaluationEntry = () => {
  const queryClient = useQueryClient();
  const updateRating = useUpdateSupplierRating();

  return useMutation({
    mutationFn: async (data: CreateSupplierEvaluationEntryData): Promise<SupplierEvaluationEntry> => {
      const { data: entry, error } = await supabase
        .from("supplier_evaluation_entries")
        .insert([data])
        .select()
        .single();

      if (error) throw error;
      return entry;
    },
    onSuccess: async (data) => {
      queryClient.invalidateQueries({ queryKey: ["supplier-evaluation-entries", data.evaluation_id] });
      queryClient.invalidateQueries({ queryKey: ["supplier-evaluation", data.evaluation_id] });
      queryClient.invalidateQueries({ queryKey: ["supplier-evaluations"] });
      
      // Get supplier_id from evaluation to update rating
      const { data: evaluation } = await supabase
        .from("supplier_evaluations")
        .select("supplier_id")
        .eq("id", data.evaluation_id)
        .single();
      
      if (evaluation) {
        updateRating.mutate(evaluation.supplier_id);
      }
      
      toast({
        title: "Success",
        description: "Evaluation entry added successfully",
      });
    },
    onError: (error: Error) => {
      toast({
        title: "Error",
        description: `Failed to add entry: ${error.message}`,
        variant: "destructive",
      });
    },
  });
};

// Update evaluation entry
export const useUpdateSupplierEvaluationEntry = () => {
  const queryClient = useQueryClient();
  const updateRating = useUpdateSupplierRating();

  return useMutation({
    mutationFn: async ({ 
      id, 
      updates 
    }: { 
      id: string; 
      updates: Partial<CreateSupplierEvaluationEntryData> 
    }): Promise<SupplierEvaluationEntry> => {
      const { data, error } = await supabase
        .from("supplier_evaluation_entries")
        .update(updates)
        .eq("id", id)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: async (data) => {
      queryClient.invalidateQueries({ queryKey: ["supplier-evaluation-entries", data.evaluation_id] });
      queryClient.invalidateQueries({ queryKey: ["supplier-evaluation", data.evaluation_id] });
      queryClient.invalidateQueries({ queryKey: ["supplier-evaluations"] });
      
      // Get supplier_id from evaluation to update rating
      const { data: evaluation } = await supabase
        .from("supplier_evaluations")
        .select("supplier_id")
        .eq("id", data.evaluation_id)
        .single();
      
      if (evaluation) {
        updateRating.mutate(evaluation.supplier_id);
      }
      
      toast({
        title: "Success",
        description: "Evaluation entry updated successfully",
      });
    },
    onError: (error: Error) => {
      toast({
        title: "Error",
        description: `Failed to update entry: ${error.message}`,
        variant: "destructive",
      });
    },
  });
};

// Delete evaluation entry
export const useDeleteSupplierEvaluationEntry = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ id, evaluationId }: { id: string; evaluationId: string }): Promise<void> => {
      const { error } = await supabase
        .from("supplier_evaluation_entries")
        .delete()
        .eq("id", id);

      if (error) throw error;
    },
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ["supplier-evaluation-entries", variables.evaluationId] });
      queryClient.invalidateQueries({ queryKey: ["supplier-evaluation", variables.evaluationId] });
      queryClient.invalidateQueries({ queryKey: ["supplier-evaluations"] });
      toast({
        title: "Success",
        description: "Evaluation entry deleted successfully",
      });
    },
    onError: (error: Error) => {
      toast({
        title: "Error",
        description: `Failed to delete entry: ${error.message}`,
        variant: "destructive",
      });
    },
  });
};