// Costume Rental sub-module types.

export type CostumeStatus = 'active' | 'inactive' | 'retired';
export type UnitCondition = 'new' | 'good' | 'fair' | 'needs_repair' | 'retired';
export type UnitStatus = 'available' | 'reserved' | 'out' | 'maintenance' | 'retired';

export interface RentalCategory {
  id: string;
  name: string;
  code: string | null;
  parent_id: string | null;
  description: string | null;
  company_id: string;
  created_by: string | null;
  created_at: string;
  updated_at: string;
}

export interface CreateRentalCategoryData {
  name: string;
  code?: string | null;
  parent_id?: string | null;
  description?: string | null;
  company_id: string;
}

export interface Costume {
  id: string;
  costume_code: string;
  name: string;
  description: string | null;
  category_id: string | null;
  size: string | null;
  color: string | null;
  gender: string | null;
  theme: string | null;
  brand: string | null;
  image_url: string | null;
  daily_rate: number;
  flat_rate: number | null;
  security_deposit: number;
  replacement_value: number;
  status: CostumeStatus;
  company_id: string;
  created_by: string | null;
  created_at: string;
  updated_at: string;
  // Optional joined/derived fields
  category?: Pick<RentalCategory, 'id' | 'name'> | null;
  units?: CostumeUnit[];
  total_units?: number;
  available_units?: number;
}

export interface CreateCostumeData {
  name: string;
  description?: string | null;
  category_id?: string | null;
  size?: string | null;
  color?: string | null;
  gender?: string | null;
  theme?: string | null;
  brand?: string | null;
  image_url?: string | null;
  daily_rate: number;
  flat_rate?: number | null;
  security_deposit?: number;
  replacement_value?: number;
  status?: CostumeStatus;
  company_id: string;
}

export interface CostumeUnit {
  id: string;
  costume_id: string;
  unit_code: string;
  condition: UnitCondition;
  status: UnitStatus;
  notes: string | null;
  company_id: string;
  created_by: string | null;
  created_at: string;
  updated_at: string;
}

export interface CreateCostumeUnitData {
  costume_id: string;
  unit_code?: string | null; // auto-generated by trigger when omitted
  condition?: UnitCondition;
  status?: UnitStatus;
  notes?: string | null;
  company_id: string;
}
