// Costume Rental sub-module types.

export type CostumeStatus = 'active' | 'inactive' | 'retired';
export type UnitCondition = 'new' | 'good' | 'fair' | 'needs_repair' | 'retired';
export type UnitStatus = 'available' | 'reserved' | 'out' | 'cleaning' | 'maintenance' | 'retired' | 'lost';
export type UnitMaintenanceType = 'cleaning' | 'repair' | 'alteration' | 'inspection';
export type UnitEventType =
  'registered' | 'status_change' | 'condition_change' | 'maintenance' | 'disposed' | 'note';

export interface RentalCategory {
  id: string;
  name: string;
  code: string | null;
  parent_id: string | null;
  description: string | null;
  company_id: string;
  created_by: string | null;
  created_at: string;
  updated_at: string;
}

export interface CreateRentalCategoryData {
  name: string;
  code?: string | null;
  parent_id?: string | null;
  description?: string | null;
  company_id: string;
}

export interface Costume {
  id: string;
  costume_code: string;
  name: string;
  description: string | null;
  category_id: string | null;
  size: string | null;
  color: string | null;
  gender: string | null;
  theme: string | null;
  brand: string | null;
  image_url: string | null;
  image_urls: string[];
  daily_rate: number;
  flat_rate: number | null;
  security_deposit: number;
  replacement_value: number;
  status: CostumeStatus;
  company_id: string;
  created_by: string | null;
  created_at: string;
  updated_at: string;
  // Optional joined/derived fields
  category?: Pick<RentalCategory, 'id' | 'name'> | null;
  units?: CostumeUnit[];
  total_units?: number;
  available_units?: number;
}

export interface CreateCostumeData {
  name: string;
  description?: string | null;
  category_id?: string | null;
  size?: string | null;
  color?: string | null;
  gender?: string | null;
  theme?: string | null;
  brand?: string | null;
  image_url?: string | null;
  image_urls?: string[];
  daily_rate: number;
  flat_rate?: number | null;
  security_deposit?: number;
  replacement_value?: number;
  status?: CostumeStatus;
  company_id: string;
}

export interface CostumeUnit {
  id: string;
  costume_id: string;
  unit_code: string;
  size: string;
  condition: UnitCondition;
  status: UnitStatus;
  notes: string | null;
  acquired_date: string | null;
  acquisition_cost: number | null;
  disposed_at: string | null;
  disposal_reason: string | null;
  disposal_method: string | null;
  disposal_value: number | null;
  company_id: string;
  created_by: string | null;
  created_at: string;
  updated_at: string;
}

export interface RentalUnitEvent {
  id: string;
  unit_id: string;
  event_type: UnitEventType;
  event_date: string;
  from_value: string | null;
  to_value: string | null;
  reference: string | null;
  notes: string | null;
  created_by: string | null;
  company_id: string | null;
  created_at: string;
}

export interface RentalUnitMaintenance {
  id: string;
  unit_id: string;
  maintenance_type: UnitMaintenanceType;
  maintenance_date: string;
  performed_by: string | null;
  provider: string | null;
  cost: number;
  description: string | null;
  out_of_service: boolean;
  company_id: string;
  created_by: string | null;
  created_at: string;
  updated_at: string;
}

export interface CreateCostumeUnitData {
  costume_id: string;
  unit_code?: string | null; // auto-generated by trigger when omitted
  size?: string;
  condition?: UnitCondition;
  status?: UnitStatus;
  notes?: string | null;
  company_id: string;
}

export type RentalOrderStatus =
  | 'draft' | 'pending_approval' | 'approved' | 'rejected'
  | 'checked_out' | 'returned' | 'completed' | 'cancelled';

export interface UnitAssignment {
  id: string;
  order_item_id: string;
  unit_id: string;
  condition_out: UnitCondition;
  condition_in: UnitCondition | null;
  returned: boolean;
  damage_notes: string | null;
  company_id: string;
  created_at: string;
  updated_at: string;
  unit?: Pick<CostumeUnit, 'id' | 'unit_code'> | null;
}

export interface RentalOrderItem {
  id: string;
  rental_order_id: string;
  costume_id: string;
  size: string;
  quantity: number;
  daily_rate: number;
  rental_days: number;
  line_total: number;
  security_deposit: number;
  preferred_unit_id: string | null;
  company_id: string;
  created_at: string;
  updated_at: string;
  costume?: Pick<Costume, 'id' | 'name' | 'costume_code' | 'image_url'> | null;
  preferred_unit?: Pick<CostumeUnit, 'id' | 'unit_code' | 'size'> | null;
  assignments?: UnitAssignment[];
}

export interface RentalOrder {
  id: string;
  rental_number: string;
  customer_id: string | null;
  status: RentalOrderStatus;
  booking_date: string;
  pickup_date: string;
  due_date: string;
  actual_return_date: string | null;
  rental_total: number;
  deposit_total: number;
  discount_amount: number;
  tax_amount: number;
  late_fee: number;
  damage_fee: number;
  deposit_refund: number;
  total_amount: number;
  /** Customer invoice raised on check-out, and the one for late / damage fees. */
  invoice_id?: string | null;
  charges_invoice_id?: string | null;
  /** Deposit actually taken, paid to invoices, and refunded. */
  deposit_received?: number;
  deposit_applied?: number;
  deposit_refunded?: number;
  deposit_settled_at?: string | null;
  pending_approval: boolean;
  approved_by: string | null;
  approved_date: string | null;
  approval_comments: string | null;
  checked_out_by: string | null;
  checked_out_at: string | null;
  returned_by: string | null;
  returned_at: string | null;
  notes: string | null;
  company_id: string;
  created_by: string | null;
  created_at: string;
  updated_at: string;
  customer?: { id: string; customer_name: string; customer_code: string } | null;
  items?: RentalOrderItem[];
}

export interface CreateRentalOrderItemInput {
  costume_id: string;
  size: string;
  quantity: number;
  daily_rate: number;
  rental_days: number;
  line_total: number;
  security_deposit: number;
  preferred_unit_id?: string | null;
}

export interface CreateRentalOrderData {
  customer_id: string | null;
  pickup_date: string;
  due_date: string;
  discount_amount?: number;
  tax_amount?: number;
  notes?: string | null;
  company_id: string;
  items: CreateRentalOrderItemInput[];
}
