import { useState } from 'react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Upload, Download, FileText, AlertCircle, CheckCircle2 } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { useWarehouseItems } from '@/hooks/useWarehouseItems';
import { useItemCategories } from '@/hooks/useItemCategories';
import { useItemUnits } from '@/hooks/useItemUnits';
import { useSuppliers } from '@/hooks/useSuppliers';
import { useCompany } from '@/contexts/CompanyContext';
import { useWarehouseLocations } from '@/hooks/useWarehouseLocations';
import { useWarehouseBins } from '@/hooks/useWarehouseBins';
import { CreateWarehouseItemData } from '@/types/itemBin';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { ScrollArea } from '@/components/ui/scroll-area';
import { supabase } from '@/integrations/supabase/client';
import { useQueryClient } from '@tanstack/react-query';
import { parseCSV, downloadCSV, allocateAutoCodes } from '@/lib/bulkImport';

interface ParsedItem extends Partial<CreateWarehouseItemData> {
  rowNumber: number;
  errors: string[];
  warnings: string[];
  initial_stock?: number;
  bin_id?: string;
  /** True when item_code was blank in CSV and will be auto-generated */
  autoGenerated?: boolean;
}

export function BulkItemImportDialog() {
  const [open, setOpen] = useState(false);
  const [csvFile, setCsvFile] = useState<File | null>(null);
  const [parsedData, setParsedData] = useState<ParsedItem[]>([]);
  const [validData, setValidData] = useState<CreateWarehouseItemData[]>([]);
  const [isProcessing, setIsProcessing] = useState(false);
  const [showPreview, setShowPreview] = useState(false);

  const { toast } = useToast();
  const { bulkCreateItemsAsync, isBulkCreating, items: existingItems = [] } = useWarehouseItems();
  const { categories } = useItemCategories();
  const { units } = useItemUnits();
  const { data: suppliers = [] } = useSuppliers();
  const { companies, selectedCompany } = useCompany();
  const { locations } = useWarehouseLocations();
  const { bins } = useWarehouseBins();
  const queryClient = useQueryClient();

  const downloadTemplate = () => {
    const headers = [
      'item_code',
      'name',
      'description',
      'category',
      'unit',
      'location',
      'initial_stock',
      'bin',
      'reorder_level',
      'min_stock_level',
      'max_stock_level',
      'unit_cost',
      'selling_price',
      'barcode',
      'sku',
      'brand',
      'manufacturer',
      'supplier',
      'status',
      'is_serialized',
      'is_batch_tracked',
      'notes',
      'company'
    ];

    const sampleRow = [
      '', // item_code: leave blank to auto-generate as INV-{CATEGORY}-{NNN}
      'Sample Item',
      'This is a sample item',
      'Electronics',
      'PCS',
      'Main Warehouse',
      '100',
      'BIN-001',
      '10',
      '5',
      '100',
      '50.00',
      '75.00',
      '123456789',
      'SKU001',
      'Sample Brand',
      'Sample Manufacturer',
      'Sample Supplier',
      'active',
      'false',
      'false',
      'Sample notes',
      'Sample Company'
    ];

    downloadCSV('item_import_template.csv', headers, [sampleRow]);
  };

  const handleFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    if (!file.name.endsWith('.csv')) {
      toast({
        title: "Error",
        description: "Please select a CSV file",
        variant: "destructive",
      });
      return;
    }

    setCsvFile(file);
    setIsProcessing(true);
    setShowPreview(false);

    try {
      const text = await file.text();
      const lines = parseCSV(text);

      if (lines.length < 2) {
        throw new Error('CSV file must contain headers and at least one data row');
      }

      const headers = lines[0].map(h => h.toLowerCase().trim());
      const dataRows = lines.slice(1);

      const parsed: ParsedItem[] = [];

      for (let i = 0; i < dataRows.length; i++) {
        const row = dataRows[i];
        const item: ParsedItem = {
          rowNumber: i + 2,
          errors: [],
          warnings: []
        };

        headers.forEach((header, idx) => {
          const value = row[idx]?.trim() || '';
          
          switch (header) {
            case 'item_code':
              if (!value) {
                // Defer: will be auto-generated based on category (INV-{CAT}-{NNN})
                item.autoGenerated = true;
              } else {
                item.item_code = value;
              }
              break;
            case 'name':
              if (!value) {
                item.errors.push('Name is required');
              } else {
                item.name = value;
              }
              break;
            case 'description':
              item.description = value || undefined;
              break;
            case 'category':
              if (value) {
                const category = categories.find(c => 
                  c.name.toLowerCase() === value.toLowerCase()
                );
                if (category) {
                  item.category_id = category.id;
                } else {
                  item.warnings.push(`Category "${value}" not found`);
                }
              }
              break;
            case 'unit':
              if (value) {
                const unit = units.find(u => 
                  u.abbreviation.toLowerCase() === value.toLowerCase()
                );
                if (unit) {
                  item.unit_id = unit.id;
                } else {
                  item.warnings.push(`Unit "${value}" not found`);
                }
              }
              break;
            case 'location':
              if (value) {
                const location = locations.find(l =>
                  (['location', 'sublocation', 'department'].includes(l.type ?? 'location')) && (
                    l.name.toLowerCase() === value.toLowerCase() ||
                    l.location_code?.toLowerCase() === value.toLowerCase()
                  )
                );
                if (location) {
                  item.location_id = location.id;
                } else {
                  item.warnings.push(`Warehouse location "${value}" not found`);
                }
              }
              break;
            case 'initial_stock':
              if (value) {
                const num = parseFloat(value);
                if (isNaN(num) || num < 0) {
                  item.errors.push('Initial stock must be a positive number');
                } else {
                  item.initial_stock = num;
                }
              }
              break;
            case 'bin':
              if (value) {
                const bin = bins.find(b => 
                  b.bin_code.toLowerCase() === value.toLowerCase() ||
                  b.name.toLowerCase() === value.toLowerCase()
                );
                if (bin) {
                  item.bin_id = bin.id;
                } else {
                  item.warnings.push(`Bin "${value}" not found`);
                }
              }
            case 'supplier':
              if (value) {
                const supplier = suppliers.find(s => 
                  s.name.toLowerCase() === value.toLowerCase()
                );
                if (supplier) {
                  item.supplier_id = supplier.id;
                } else {
                  item.warnings.push(`Supplier "${value}" not found`);
                }
              }
              break;
            case 'company':
              if (value) {
                const company = companies.find(c => 
                  c.name.toLowerCase() === value.toLowerCase()
                );
                if (company) {
                  item.company_id = company.id;
                } else {
                  item.warnings.push(`Company "${value}" not found`);
                }
              }
              break;
            case 'reorder_level':
            case 'min_stock_level':
            case 'max_stock_level':
              if (value) {
                const num = parseFloat(value);
                if (isNaN(num)) {
                  item.errors.push(`${header} must be a number`);
                } else {
                  (item as any)[header] = num;
                }
              }
              break;
            case 'unit_cost':
            case 'selling_price':
              if (value) {
                const num = parseFloat(value);
                if (isNaN(num)) {
                  item.errors.push(`${header} must be a number`);
                } else {
                  (item as any)[header] = num;
                }
              }
              break;
            case 'status':
              if (value) {
                if (['active', 'inactive', 'discontinued'].includes(value.toLowerCase())) {
                  (item as any).status = value.toLowerCase();
                } else {
                  item.errors.push('Status must be: active, inactive, or discontinued');
                }
              } else {
                (item as any).status = 'active';
              }
              break;
            case 'is_serialized':
            case 'is_batch_tracked':
              if (value) {
                const boolValue = value.toLowerCase() === 'true';
                (item as any)[header] = boolValue;
              }
              break;
            case 'barcode':
            case 'sku':
            case 'brand':
            case 'manufacturer':
            case 'notes':
              (item as any)[header] = value || undefined;
              break;
          }
        });

        // Validate: warn if initial_stock specified without a valid bin
        if (item.initial_stock && item.initial_stock > 0 && !item.bin_id) {
          item.warnings.push('Initial stock specified but no valid bin provided - stock will not be set');
        }

        parsed.push(item);
      }

      // Validation guard: rows needing auto-generation MUST have a resolved category
      parsed.forEach(item => {
        if (item.autoGenerated && !item.category_id) {
          item.errors.push(
            'Item code is required when category is missing — provide an item_code or set a valid category for auto-generation'
          );
        }
      });

      // Allocate auto-generated codes per (category, company) group via the
      // shared bulk-import pipeline. Sequential codes prevent in-batch collisions.
      await allocateAutoCodes(parsed as any, categories, {
        scope: 'inventory',
        defaultCompanyId: selectedCompany?.id ?? null,
      });

      // Check for duplicate item_codes within the CSV file (now includes auto-generated)
      const itemCodeCounts = new Map<string, number>();
      parsed.forEach(item => {
        if (item.item_code) {
          const key = `${item.item_code?.toLowerCase()}_${item.company_id || selectedCompany?.id || ''}`;
          itemCodeCounts.set(key, (itemCodeCounts.get(key) || 0) + 1);
        }
      });

      // Mark duplicates within CSV and existing items in database
      parsed.forEach(item => {
        if (item.item_code) {
          const companyId = item.company_id || selectedCompany?.id || '';
          const key = `${item.item_code.toLowerCase()}_${companyId}`;
          
          // Check for duplicates within the CSV
          if ((itemCodeCounts.get(key) || 0) > 1) {
            item.errors.push(`Duplicate item code "${item.item_code}" in CSV`);
          }
          
          // Check if item_code already exists in the database for this company
          const existsInDb = existingItems.some(
            existing => existing.item_code?.toLowerCase() === item.item_code?.toLowerCase() &&
                       existing.company_id === companyId
          );
          if (existsInDb) {
            item.errors.push(`Item code "${item.item_code}" already exists in database`);
          }
        }
      });

      setParsedData(parsed);
      
      const valid = parsed
        .filter(item => item.errors.length === 0)
        .map(({ rowNumber, errors, warnings, initial_stock, bin_id, autoGenerated, ...item }) => item as CreateWarehouseItemData);
      
      setValidData(valid);
      setShowPreview(true);

      toast({
        title: "CSV Parsed",
        description: `Found ${parsed.length} rows: ${valid.length} valid, ${parsed.length - valid.length} with errors`,
      });
    } catch (error: any) {
      console.error('Error parsing CSV:', error);
      toast({
        title: "Error",
        description: error.message || "Failed to parse CSV file",
        variant: "destructive",
      });
    } finally {
      setIsProcessing(false);
    }
  };

  const handleImport = async () => {
    if (validData.length === 0) {
      toast({
        title: "Error",
        description: "No valid items to import",
        variant: "destructive",
      });
      return;
    }

    try {
      // Step 1: Create items
      const createdItems = await bulkCreateItemsAsync(validData);
      
      // Step 2: Create bin allocations for items with initial stock
      const { data: user } = await supabase.auth.getUser();
      
      const binAllocations: Array<{
        warehouse_item_id: string;
        bin_id: string;
        allocated_quantity: number;
        company_id?: string;
        created_by?: string;
      }> = [];
      
      for (const createdItem of createdItems) {
        // Find the original parsed item by item_code to get initial_stock and bin_id
        const originalItem = parsedData.find(p => 
          p.item_code === createdItem.item_code && 
          p.errors.length === 0
        );
        
        if (originalItem?.initial_stock && originalItem.initial_stock > 0 && originalItem?.bin_id) {
          binAllocations.push({
            warehouse_item_id: createdItem.id,
            bin_id: originalItem.bin_id,
            allocated_quantity: originalItem.initial_stock,
            company_id: selectedCompany?.id,
            created_by: user.user?.id,
          });
        }
      }
      
      // Step 3: Bulk insert bin allocations if any
      if (binAllocations.length > 0) {
        const { error } = await supabase
          .from('warehouse_bin_allocations')
          .insert(binAllocations);
        
        if (error) {
          console.error('Error creating bin allocations:', error);
          toast({
            title: "Partial Success",
            description: `Items imported but some initial stock could not be set: ${error.message}`,
          });
        }
        
        // Invalidate queries to refresh data
        queryClient.invalidateQueries({ queryKey: ['warehouse-bin-allocations'] });
      }

      // Step 4: Update current_stock for items with initial stock
      for (const createdItem of createdItems) {
        const originalItem = parsedData.find(p => 
          p.item_code === createdItem.item_code && 
          p.errors.length === 0
        );
        
        if (originalItem?.initial_stock && originalItem.initial_stock > 0) {
          await supabase
            .from('warehouse_items')
            .update({ current_stock: originalItem.initial_stock })
            .eq('id', createdItem.id);
        }
      }

      // Invalidate warehouse items query to refresh data
      queryClient.invalidateQueries({ queryKey: ['warehouse-items'] });
      
      setOpen(false);
      resetState();
    } catch (error) {
      // Error handled by mutation
    }
  };

  const resetState = () => {
    setCsvFile(null);
    setParsedData([]);
    setValidData([]);
    setShowPreview(false);
  };

  const handleOpenChange = (newOpen: boolean) => {
    setOpen(newOpen);
    if (!newOpen) {
      resetState();
    }
  };

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogTrigger asChild>
        <Button variant="outline">
          <Upload className="mr-2 h-4 w-4" />
          Bulk Import
        </Button>
      </DialogTrigger>
      <DialogContent className="max-w-4xl max-h-[85vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Bulk Import Items from CSV</DialogTitle>
          <DialogDescription>
            Upload a CSV file to import multiple items at once. Download the template to get started.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4">
          <Alert>
            <AlertCircle className="h-4 w-4" />
            <AlertDescription>
              Leave <code className="font-mono text-xs">item_code</code> blank to auto-generate codes
              following the standard <code className="font-mono text-xs">INV-{'{CATEGORY}'}-{'{SEQUENCE}'}</code>
              {' '}(GS1 / ISO 8000-110). A valid <code className="font-mono text-xs">category</code> is required for auto-generation.
            </AlertDescription>
          </Alert>

          <div className="flex items-center gap-4">
            <Button variant="outline" onClick={downloadTemplate} className="flex-shrink-0">
              <Download className="mr-2 h-4 w-4" />
              Download Template
            </Button>

            <div className="flex-1">
              <Label htmlFor="csv-file" className="sr-only">CSV File</Label>
              <Input
                id="csv-file"
                type="file"
                accept=".csv"
                onChange={handleFileChange}
                disabled={isProcessing || isBulkCreating}
              />
            </div>
          </div>

          {showPreview && parsedData.length > 0 && (
            <div className="space-y-4">
              <div className="flex items-center gap-4">
                <Badge variant="outline" className="flex items-center gap-1">
                  <FileText className="h-3 w-3" />
                  Total: {parsedData.length}
                </Badge>
                <Badge variant="default" className="flex items-center gap-1 bg-green-100 text-green-800 border-green-200">
                  <CheckCircle2 className="h-3 w-3" />
                  Valid: {validData.length}
                </Badge>
                <Badge variant="destructive" className="flex items-center gap-1">
                  <AlertCircle className="h-3 w-3" />
                  Errors: {parsedData.length - validData.length}
                </Badge>
              </div>

              {parsedData.some(item => item.errors.length > 0) && (
                <Alert variant="destructive">
                  <AlertCircle className="h-4 w-4" />
                  <AlertDescription>
                    Some rows contain errors and will be skipped during import. Please review and fix the errors in your CSV file.
                  </AlertDescription>
                </Alert>
              )}

              <ScrollArea className="h-[400px] border rounded-lg">
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead className="w-16">Row</TableHead>
                      <TableHead>Item Code</TableHead>
                      <TableHead>Name</TableHead>
                      <TableHead>Category</TableHead>
                      <TableHead>Unit</TableHead>
                      <TableHead>Status</TableHead>
                      <TableHead>Validation</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {parsedData.map((item) => (
                      <TableRow key={item.rowNumber} className={item.errors.length > 0 ? 'bg-red-50' : 'bg-green-50'}>
                        <TableCell className="font-mono text-xs">{item.rowNumber}</TableCell>
                        <TableCell className="font-medium">
                          <div className="flex items-center gap-2">
                            <span>{item.item_code || '-'}</span>
                            {item.autoGenerated && item.item_code && (
                              <Badge variant="secondary" className="text-[10px] px-1.5 py-0 h-4">
                                Auto
                              </Badge>
                            )}
                          </div>
                        </TableCell>
                        <TableCell>{item.name || '-'}</TableCell>
                        <TableCell>
                          {item.category_id 
                            ? categories.find(c => c.id === item.category_id)?.name
                            : '-'
                          }
                        </TableCell>
                        <TableCell>
                          {item.unit_id 
                            ? units.find(u => u.id === item.unit_id)?.abbreviation
                            : '-'
                          }
                        </TableCell>
                        <TableCell>
                          <Badge className={
                            item.status === 'active' ? 'bg-green-100 text-green-800 border-green-200' :
                            item.status === 'inactive' ? 'bg-gray-100 text-gray-800 border-gray-200' :
                            'bg-red-100 text-red-800 border-red-200'
                          }>
                            {item.status || 'active'}
                          </Badge>
                        </TableCell>
                        <TableCell>
                          <div className="space-y-1">
                            {item.errors.map((error, idx) => (
                              <div key={idx} className="flex items-center gap-1 text-xs text-red-600">
                                <AlertCircle className="h-3 w-3" />
                                {error}
                              </div>
                            ))}
                            {item.warnings.map((warning, idx) => (
                              <div key={idx} className="flex items-center gap-1 text-xs text-yellow-600">
                                <AlertCircle className="h-3 w-3" />
                                {warning}
                              </div>
                            ))}
                            {item.errors.length === 0 && item.warnings.length === 0 && (
                              <div className="flex items-center gap-1 text-xs text-green-600">
                                <CheckCircle2 className="h-3 w-3" />
                                Valid
                              </div>
                            )}
                          </div>
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </ScrollArea>

              <div className="flex justify-end gap-2">
                <Button variant="outline" onClick={() => handleOpenChange(false)} disabled={isBulkCreating}>
                  Cancel
                </Button>
                <Button 
                  onClick={handleImport} 
                  disabled={validData.length === 0 || isBulkCreating}
                >
                  {isBulkCreating ? 'Importing...' : `Import ${validData.length} Items`}
                </Button>
              </div>
            </div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}
