// Stock Movement Ledger PDF generator (IAS 2 / SAP MB51 inspired layout)
// Deno-compatible — uses pdf-lib (no native deps).
import { PDFDocument, StandardFonts, rgb, PDFFont, PDFPage } from "https://esm.sh/pdf-lib@1.17.1";

export interface LedgerRow {
  date: string;          // ISO
  docNo: string;
  refType: string;
  description: string;
  inQty: number;
  outQty: number;
  uom: string;
  unitCost: number;
  value: number;
}

export interface LedgerItemSection {
  itemCode: string;
  itemName: string;
  uom: string;
  rows: LedgerRow[];
  totalIn: number;
  totalOut: number;
}

export interface LedgerLocationSection {
  locationName: string;
  items: LedgerItemSection[];
}

export interface LedgerInput {
  companyName: string;
  periodFrom: string;     // YYYY-MM-DD
  periodTo: string;       // YYYY-MM-DD (inclusive)
  generatedAt: string;    // ISO 8601
  currency: string;
  sections: LedgerLocationSection[];
  totals: { in: number; out: number; netValue: number };
}

const A4_LANDSCAPE = { w: 841.89, h: 595.28 };
const MARGIN = 28;
const ROW_H = 13;
const HEADER_H = 60;
const FOOTER_H = 22;

// Page width 841.89 - 2*28 margin = 785.89pt available
const COLS = [
  { key: "date",    label: "Date",        w: 60,  align: "left"  as const },
  { key: "docNo",   label: "Doc #",       w: 85,  align: "left"  as const },
  { key: "refType", label: "Type",        w: 70,  align: "left"  as const },
  { key: "desc",    label: "Description", w: 210, align: "left"  as const },
  { key: "in",      label: "In Qty",      w: 60,  align: "right" as const },
  { key: "out",     label: "Out Qty",     w: 60,  align: "right" as const },
  { key: "uom",     label: "UOM",         w: 40,  align: "left"  as const },
  { key: "cost",    label: "Unit Cost",   w: 70,  align: "right" as const },
  { key: "value",   label: "Value",       w: 80,  align: "right" as const },
];
const TABLE_W = COLS.reduce((s, c) => s + c.w, 0);

const fmtN = (n: number, d = 2) =>
  (Number(n) || 0).toLocaleString("en-US", { minimumFractionDigits: d, maximumFractionDigits: d });

function sanitize(s: string): string {
  // pdf-lib StandardFonts only support WinAnsi. Strip anything outside it (emoji, CJK, etc.)
  // and replace common typographic chars with ASCII equivalents.
  return String(s ?? "")
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u201C\u201D]/g, '"')
    .replace(/[\u2013\u2014]/g, "-")
    .replace(/\u2026/g, "...")
    .replace(/[^\x20-\x7E\xA0-\xFF]/g, "");
}

function truncate(s: string, font: PDFFont, size: number, maxW: number): string {
  s = sanitize(s);
  if (font.widthOfTextAtSize(s, size) <= maxW) return s;
  let lo = 0, hi = s.length;
  while (lo < hi) {
    const mid = (lo + hi + 1) >> 1;
    if (font.widthOfTextAtSize(s.slice(0, mid) + "...", size) <= maxW) lo = mid;
    else hi = mid - 1;
  }
  return s.slice(0, lo) + "...";
}

export async function buildStockLedgerPdf(input: LedgerInput): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

  const pages: PDFPage[] = [];
  let page = pdf.addPage([A4_LANDSCAPE.w, A4_LANDSCAPE.h]);
  pages.push(page);
  let y = A4_LANDSCAPE.h - MARGIN;

  const drawHeader = () => {
    page.drawText(sanitize(input.companyName), { x: MARGIN, y: y - 12, size: 13, font: bold, color: rgb(0.1, 0.1, 0.2) });
    page.drawText("STOCK MOVEMENT LEDGER", { x: MARGIN, y: y - 28, size: 11, font: bold });
    const meta = `Period: ${input.periodFrom} -> ${input.periodTo}   |   Currency: ${input.currency}   |   Generated: ${input.generatedAt}`;
    page.drawText(sanitize(meta), { x: MARGIN, y: y - 44, size: 8, font, color: rgb(0.3, 0.3, 0.3) });
    page.drawLine({
      start: { x: MARGIN, y: y - 50 }, end: { x: A4_LANDSCAPE.w - MARGIN, y: y - 50 },
      thickness: 0.6, color: rgb(0.6, 0.6, 0.6),
    });
    y -= HEADER_H;
  };

  const drawTableHeader = () => {
    let x = MARGIN;
    page.drawRectangle({ x, y: y - ROW_H + 2, width: TABLE_W, height: ROW_H, color: rgb(0.92, 0.94, 0.98) });
    for (const c of COLS) {
      const tx = c.align === "right" ? x + c.w - 4 - bold.widthOfTextAtSize(c.label, 8) : x + 4;
      page.drawText(c.label, { x: tx, y: y - ROW_H + 5, size: 8, font: bold });
      x += c.w;
    }
    y -= ROW_H;
  };

  const drawFooter = (pageIdx: number, total: number) => {
    const txt = `Page ${pageIdx + 1} of ${total}   |   Generated by Lyceum Global Holdings   |   ${input.generatedAt}`;
    page.drawText(sanitize(txt), { x: MARGIN, y: MARGIN - 14, size: 7, font, color: rgb(0.45, 0.45, 0.45) });
  };

  const newPage = () => {
    page = pdf.addPage([A4_LANDSCAPE.w, A4_LANDSCAPE.h]);
    pages.push(page);
    y = A4_LANDSCAPE.h - MARGIN;
    drawHeader();
    drawTableHeader();
  };

  const ensureSpace = (needed: number) => {
    if (y - needed < MARGIN + FOOTER_H) newPage();
  };

  const drawRow = (cells: string[], opts: { bold?: boolean; bg?: [number, number, number] } = {}) => {
    ensureSpace(ROW_H);
    let x = MARGIN;
    if (opts.bg) {
      page.drawRectangle({ x, y: y - ROW_H + 2, width: TABLE_W, height: ROW_H, color: rgb(...opts.bg) });
    }
    const f = opts.bold ? bold : font;
    for (let i = 0; i < COLS.length; i++) {
      const c = COLS[i];
      const txt = truncate(cells[i] ?? "", f, 8, c.w - 8);
      const tx = c.align === "right" ? x + c.w - 4 - f.widthOfTextAtSize(txt, 8) : x + 4;
      page.drawText(txt, { x: tx, y: y - ROW_H + 5, size: 8, font: f });
      x += c.w;
    }
    page.drawLine({
      start: { x: MARGIN, y: y - ROW_H + 1 }, end: { x: MARGIN + TABLE_W, y: y - ROW_H + 1 },
      thickness: 0.2, color: rgb(0.85, 0.85, 0.85),
    });
    y -= ROW_H;
  };

  const drawSectionLabel = (text: string, size = 10) => {
    ensureSpace(20);
    page.drawText(sanitize(text), { x: MARGIN, y: y - 12, size, font: bold, color: rgb(0.1, 0.2, 0.4) });
    y -= 18;
  };

  // === Render ===
  drawHeader();

  if (input.sections.length === 0) {
    page.drawText("No stock movements recorded for this period.", {
      x: MARGIN, y: y - 20, size: 10, font, color: rgb(0.4, 0.4, 0.4),
    });
  }

  for (const loc of input.sections) {
    for (const item of loc.items) {
      drawSectionLabel(`${item.itemCode} — ${item.itemName}`, 9);
      drawTableHeader();
      // Movements
      for (const r of item.rows) {
        drawRow([
          r.date.slice(0, 10), r.docNo, r.refType, r.description,
          r.inQty ? fmtN(r.inQty) : "", r.outQty ? fmtN(r.outQty) : "",
          r.uom, fmtN(r.unitCost), fmtN(r.value),
        ]);
      }
      // Subtotal
      drawRow([
        "", "", "TOTAL", `In: ${fmtN(item.totalIn)} | Out: ${fmtN(item.totalOut)}`,
        fmtN(item.totalIn), fmtN(item.totalOut), item.uom, "", "",
      ], { bold: true, bg: [0.93, 0.96, 0.93] });
      y -= 6; // spacing between items
    }
    y -= 8;
  }

  // Grand totals
  ensureSpace(40);
  page.drawLine({
    start: { x: MARGIN, y: y - 4 }, end: { x: A4_LANDSCAPE.w - MARGIN, y: y - 4 },
    thickness: 0.6, color: rgb(0.4, 0.4, 0.4),
  });
  y -= 14;
  page.drawText(
    `GRAND TOTALS — Receipts: ${fmtN(input.totals.in)}   |   Issues: ${fmtN(input.totals.out)}   |   Net Movement Value: ${input.currency} ${fmtN(input.totals.netValue)}`,
    { x: MARGIN, y: y - 8, size: 9, font: bold },
  );

  // Footers
  const total = pages.length;
  for (let i = 0; i < pages.length; i++) {
    page = pages[i];
    const txt = `Page ${i + 1} of ${total}   |   Generated by Lyceum Global Holdings   |   ${input.generatedAt}`;
    page.drawText(sanitize(txt), { x: MARGIN, y: MARGIN - 14, size: 7, font, color: rgb(0.45, 0.45, 0.45) });
  }

  return await pdf.save();
}
