import { ReportEnvelope } from "./types";
import { formatValue } from "./format";

/**
 * RFC 4180 CSV with UTF-8 BOM for Excel compatibility.
 * Header rows (envelope metadata) are prefixed with `#` so downstream parsers can skip them.
 */
export function renderCsv(envelope: ReportEnvelope, fileName: string): void {
  const lines: string[] = [];
  lines.push(`# ${envelope.companyName} — ${envelope.title}`);
  lines.push(`# Report Code: ${envelope.reportCode}`);
  if (envelope.standard) lines.push(`# Standard: ${envelope.standard}`);
  lines.push(`# Currency: ${envelope.currency}`);
  if (envelope.periodStart || envelope.periodEnd) {
    lines.push(`# Period: ${envelope.periodStart ?? ""} to ${envelope.periodEnd ?? ""}`);
  }
  if (envelope.filters.length) {
    lines.push(`# Filters: ${envelope.filters.map((f) => `${f.label}=${f.value}`).join(" | ")}`);
  }
  lines.push(`# Generated by ${envelope.generatedBy} at ${envelope.generatedAt}`);
  lines.push("");

  lines.push(envelope.columns.map((c) => csvEscape(c.label)).join(","));

  envelope.rows.forEach((row) => {
    lines.push(
      envelope.columns
        .map((c) => csvEscape(formatValue(row[c.key], c, envelope.currency)))
        .join(","),
    );
  });

  if (envelope.totals) {
    lines.push(
      envelope.columns
        .map((c, i) => {
          const v = envelope.totals?.[c.key];
          if (v === undefined && i === 0) return csvEscape("Total");
          return csvEscape(v === undefined || v === null ? "" : formatValue(v, c, envelope.currency));
        })
        .join(","),
    );
  }

  if (envelope.notes?.length) {
    lines.push("");
    lines.push("# Methodology:");
    envelope.notes.forEach((n) => lines.push(`# - ${n}`));
  }

  const csv = "\uFEFF" + lines.join("\r\n");
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function csvEscape(s: string): string {
  if (s == null) return "";
  if (/[",\r\n]/.test(s)) {
    return `"${s.replace(/"/g, '""')}"`;
  }
  return s;
}
