import { ReportEnvelope } from "./types";
import { formatValue } from "./format";

/**
 * Render report as PDF using jspdf + autoTable (already in the project).
 * Lazy-imported to keep the main bundle small.
 */
export async function renderPdf(envelope: ReportEnvelope, fileName: string): Promise<void> {
  const [{ default: jsPDF }, autoTableMod] = await Promise.all([
    import("jspdf"),
    import("jspdf-autotable"),
  ]);
  const autoTable = (autoTableMod as { default: any }).default ?? (autoTableMod as any);

  // A4 landscape for wide tables, portrait for narrow ones; very wide
  // analytical reports (e.g. the 1/3/6/12-month price trend) move to A3.
  const colCount = envelope.columns.length;
  const orientation = colCount > 6 ? "landscape" : "portrait";
  const format = colCount > 16 ? "a3" : "a4";
  const bodyFontSize = colCount > 20 ? 6.5 : colCount > 12 ? 7 : 8;
  const doc = new jsPDF({ orientation, unit: "pt", format });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 32;

  // ---- Header block ----
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text(`${envelope.companyName} — ${envelope.title}`, margin, 40);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(80);
  doc.text(
    `Report Code: ${envelope.reportCode}` +
      (envelope.standard ? `   |   Standard: ${envelope.standard}` : "") +
      `   |   Currency: ${envelope.currency} (ISO 4217)`,
    margin,
    58,
  );

  const periodLine =
    envelope.periodStart || envelope.periodEnd
      ? `Period: ${envelope.periodStart ?? "—"} → ${envelope.periodEnd ?? "—"} (ISO 8601)`
      : `As of: ${envelope.generatedAt}`;
  doc.text(periodLine, margin, 72);

  const filtersLine =
    "Filters: " +
    (envelope.filters.length
      ? envelope.filters.map((f) => `${f.label}=${f.value}`).join("  |  ")
      : "None");
  doc.text(filtersLine, margin, 86);

  doc.text(`Generated by ${envelope.generatedBy} at ${envelope.generatedAt}`, margin, 100);

  // Divider
  doc.setDrawColor(200);
  doc.line(margin, 108, pageWidth - margin, 108);

  // ---- Body ----
  const head = [envelope.columns.map((c) => c.label)];
  const body = envelope.rows.map((row) =>
    envelope.columns.map((c) => formatValue(row[c.key], c, envelope.currency)),
  );
  const foot =
    envelope.totals !== undefined
      ? [
          envelope.columns.map((c, i) => {
            const v = envelope.totals?.[c.key];
            if (v === undefined && i === 0) return "Total";
            return v === undefined || v === null ? "" : formatValue(v, c, envelope.currency);
          }),
        ]
      : undefined;

  autoTable(doc, {
    startY: 120,
    head,
    body,
    foot,
    margin: { left: margin, right: margin },
    styles: { fontSize: bodyFontSize, cellPadding: colCount > 12 ? 3 : 4, overflow: "linebreak" },
    headStyles: { fillColor: [31, 41, 55], textColor: 255, fontStyle: "bold" },
    footStyles: { fillColor: [243, 244, 246], textColor: 0, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [247, 247, 247] },
    didDrawPage: (data: { pageNumber: number }) => {
      const pageHeight = doc.internal.pageSize.getHeight();
      doc.setFontSize(8);
      doc.setTextColor(120);
      doc.text(
        `Lyceum ERP  ·  Confidential — Internal Use  ·  Source: Lyceum ERP`,
        margin,
        pageHeight - 18,
      );
      doc.text(
        `Page ${data.pageNumber} of ${doc.getNumberOfPages()}`,
        pageWidth - margin,
        pageHeight - 18,
        { align: "right" },
      );
      doc.text(
        `Signature: __________________________   Date: __________`,
        margin,
        pageHeight - 32,
      );
    },
  });

  // ---- Methodology notes (ISO 9001 §7.5) ----
  if (envelope.notes?.length) {
    const pageHeight = doc.internal.pageSize.getHeight();
    const maxWidth = pageWidth - margin * 2;
    let y = ((doc as any).lastAutoTable?.finalY ?? 120) + 20;
    const entries = ["Methodology", ...envelope.notes.map((n) => `•  ${n}`)];
    doc.setFontSize(8);
    entries.forEach((text, i) => {
      const wrapped = doc.splitTextToSize(text, maxWidth) as string[];
      // Keep clear of the signature/footer band drawn on each page.
      if (y + wrapped.length * 10 > pageHeight - 48) {
        doc.addPage();
        y = 40;
      }
      doc.setFont("helvetica", i === 0 ? "bold" : "normal");
      doc.setTextColor(i === 0 ? 40 : 90);
      doc.text(wrapped, margin, y);
      y += wrapped.length * 10 + 2;
    });
  }

  doc.save(fileName);
}
