// Shared types for the Reports Center
// All reports flow through this envelope so output stays standards-compliant.

export type ReportFormat = "xlsx" | "pdf" | "csv" | "preview";

export interface ReportColumn {
  /** Field key in the row object */
  key: string;
  /** Header label shown in the output */
  label: string;
  /** Optional formatter for the value (string, number, date, currency, percent) */
  type?: "string" | "number" | "currency" | "date" | "datetime" | "percent" | "integer";
  /** Optional column width for XLSX */
  width?: number;
  /** ISO 4217 code; only used when type === "currency". Defaults to envelope currency. */
  currency?: string;
  /** Right-align numeric output */
  align?: "left" | "right" | "center";
}

export interface ReportFilterDescriptor {
  label: string;
  value: string;
}

export interface ReportEnvelope {
  /** Stable code: e.g. WH-INV-VAL-001 */
  reportCode: string;
  /** Human title */
  title: string;
  /** Module the report belongs to (warehouse, finance, ...) */
  moduleKey: string;
  /** Standard reference (e.g. "IFRS / IAS 2") */
  standard?: string;
  /** Company name displayed in header */
  companyName: string;
  /** ISO 4217 currency code used across the report */
  currency: string;
  /** ISO 8601 period describing the data window */
  periodStart?: string; // YYYY-MM-DD
  periodEnd?: string;   // YYYY-MM-DD
  /** Filters applied (rendered in header) */
  filters: ReportFilterDescriptor[];
  /** Generated by user identifier (email or name) */
  generatedBy: string;
  /** Generation timestamp (ISO 8601 UTC) */
  generatedAt: string;
  /** Columns describing the body table */
  columns: ReportColumn[];
  /** Body rows */
  rows: Record<string, unknown>[];
  /** Optional totals row keyed by column key */
  totals?: Record<string, unknown>;
  /**
   * Optional per-column substring(s) to highlight in the on-screen preview.
   * Keyed by column key; value is one or more terms (case-insensitive).
   * Preview-only — XLSX/PDF/CSV exports remain plain text.
   */
  highlightTerms?: Record<string, string[]>;
  /**
   * When true, the highlighter wraps the entire matched cell (used for the
   * "equals" operator). Defaults to per-substring highlighting.
   */
  highlightWholeCell?: boolean;
}

/** Operators supported by the advanced notes filter. */
export type NotesFilterOp =
  | "contains"
  | "equals"
  | "startsWith"
  | "endsWith"
  | "notContains";

/** Value shape stored under a `textOperator` parameter key. */
export interface NotesFilterValue {
  op: NotesFilterOp;
  term: string;
}

/** Value shape stored under a `binMulti` parameter key. */
export interface BinMultiValue {
  mode: "include" | "exclude";
  binIds: string[];
}
