import ExcelJS from "exceljs";
import { ReportEnvelope } from "./types";
import { excelNumFmt } from "./format";

/**
 * Render a report envelope as a downloadable XLSX file.
 * Layout (ISO 9001 §7.5 documented information):
 *   Row 1: Company · Title (merged, bold, large)
 *   Row 2: Report Code  |  Standard
 *   Row 3: Period
 *   Row 4: Filters
 *   Row 5: Generated By / Generated At (UTC, ISO 8601)
 *   Row 6: blank
 *   Row 7: column headers (frozen)
 *   Row 8+: data
 *   Last:  totals (bold, top border)
 */
export async function renderXlsx(envelope: ReportEnvelope, fileName: string): Promise<void> {
  const wb = new ExcelJS.Workbook();
  wb.creator = "Lyceum ERP — Reports Center";
  wb.created = new Date();

  const ws = wb.addWorksheet(envelope.title.slice(0, 31));

  const totalCols = envelope.columns.length || 1;
  const lastColLetter = colLetter(totalCols);

  // ---------- Header block ----------
  ws.mergeCells(`A1:${lastColLetter}1`);
  const titleCell = ws.getCell("A1");
  titleCell.value = `${envelope.companyName} — ${envelope.title}`;
  titleCell.font = { bold: true, size: 14 };
  titleCell.alignment = { vertical: "middle", horizontal: "left" };

  ws.mergeCells(`A2:${lastColLetter}2`);
  ws.getCell("A2").value =
    `Report Code: ${envelope.reportCode}` +
    (envelope.standard ? `   ·   Standard: ${envelope.standard}` : "") +
    `   ·   Currency: ${envelope.currency} (ISO 4217)`;
  ws.getCell("A2").font = { italic: true, size: 10 };

  ws.mergeCells(`A3:${lastColLetter}3`);
  ws.getCell("A3").value =
    envelope.periodStart || envelope.periodEnd
      ? `Period: ${envelope.periodStart ?? "—"} → ${envelope.periodEnd ?? "—"} (ISO 8601)`
      : "Period: as of " + envelope.generatedAt;
  ws.getCell("A3").font = { size: 10 };

  ws.mergeCells(`A4:${lastColLetter}4`);
  ws.getCell("A4").value =
    "Filters: " +
    (envelope.filters.length
      ? envelope.filters.map((f) => `${f.label}=${f.value}`).join("  ·  ")
      : "None");
  ws.getCell("A4").font = { size: 10 };

  ws.mergeCells(`A5:${lastColLetter}5`);
  ws.getCell("A5").value = `Generated by ${envelope.generatedBy}  ·  ${envelope.generatedAt}`;
  ws.getCell("A5").font = { size: 10, color: { argb: "FF666666" } };

  // ---------- Column headers ----------
  const headerRowIdx = 7;
  const headerRow = ws.getRow(headerRowIdx);
  envelope.columns.forEach((col, i) => {
    const cell = headerRow.getCell(i + 1);
    cell.value = col.label;
    cell.font = { bold: true, color: { argb: "FFFFFFFF" } };
    cell.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FF1F2937" },
    };
    cell.alignment = { vertical: "middle", horizontal: col.align ?? "left" };
    cell.border = {
      top: { style: "thin" },
      bottom: { style: "thin" },
      left: { style: "thin" },
      right: { style: "thin" },
    };
  });
  headerRow.height = 22;

  // Freeze header
  ws.views = [{ state: "frozen", ySplit: headerRowIdx, xSplit: 0 }];

  // ---------- Data rows ----------
  envelope.rows.forEach((row, rIdx) => {
    const r = ws.getRow(headerRowIdx + 1 + rIdx);
    envelope.columns.forEach((col, cIdx) => {
      const cell = r.getCell(cIdx + 1);
      const raw = row[col.key];
      cell.value = toExcelValue(raw, col.type) as ExcelJS.CellValue;
      const fmt = excelNumFmt(col, envelope.currency);
      if (fmt) cell.numFmt = fmt;
      cell.alignment = {
        vertical: "middle",
        horizontal:
          col.align ??
          (col.type === "number" || col.type === "currency" || col.type === "integer"
            ? "right"
            : "left"),
      };
      // zebra striping
      if (rIdx % 2 === 1) {
        cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFF7F7F7" } };
      }
    });
  });

  // ---------- Totals ----------
  if (envelope.totals) {
    const totalsRow = ws.getRow(headerRowIdx + 1 + envelope.rows.length);
    envelope.columns.forEach((col, cIdx) => {
      const cell = totalsRow.getCell(cIdx + 1);
      const value = envelope.totals?.[col.key];
      if (cIdx === 0 && value === undefined) {
        cell.value = "Total";
      } else if (value !== undefined && value !== null) {
        cell.value = toExcelValue(value, col.type) as ExcelJS.CellValue;
        const fmt = excelNumFmt(col, envelope.currency);
        if (fmt) cell.numFmt = fmt;
      }
      cell.font = { bold: true };
      cell.border = { top: { style: "double" } };
      cell.alignment = {
        horizontal:
          col.align ??
          (col.type === "number" || col.type === "currency" || col.type === "integer"
            ? "right"
            : "left"),
      };
    });
  }

  // Auto-width
  ws.columns.forEach((col, i) => {
    const explicit = envelope.columns[i]?.width;
    if (explicit) {
      col.width = explicit;
      return;
    }
    let max = envelope.columns[i]?.label.length ?? 10;
    col.eachCell?.({ includeEmpty: false }, (cell) => {
      const v = cell.value == null ? "" : String(cell.value);
      if (v.length > max) max = Math.min(v.length, 60);
    });
    col.width = max + 2;
  });

  const buffer = await wb.xlsx.writeBuffer();
  download(buffer as ArrayBuffer, fileName, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
}

function toExcelValue(raw: unknown, type?: string): unknown {
  if (raw === null || raw === undefined || raw === "") return null;
  if (type === "date" || type === "datetime") {
    const d = new Date(String(raw));
    return isNaN(d.getTime()) ? String(raw) : d;
  }
  if (type === "number" || type === "integer" || type === "currency" || type === "percent") {
    const n = Number(raw);
    return isNaN(n) ? null : n;
  }
  return raw;
}

function colLetter(n: number): string {
  let s = "";
  while (n > 0) {
    const m = (n - 1) % 26;
    s = String.fromCharCode(65 + m) + s;
    n = Math.floor((n - 1) / 26);
  }
  return s;
}

function download(buffer: ArrayBuffer, fileName: string, mime: string) {
  const blob = new Blob([buffer], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
