import { ReportEnvelope } from "@/lib/reports/types";
import { formatValue } from "@/lib/reports/format";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { cn } from "@/lib/utils";

interface Props {
  envelope: ReportEnvelope;
}

export function ReportPreviewTable({ envelope }: Props) {
  return (
    <div className="rounded-lg border bg-card">
      <div className="border-b p-4 space-y-1">
        <div className="text-base font-semibold">
          {envelope.companyName} — {envelope.title}
        </div>
        <div className="text-xs text-muted-foreground">
          {envelope.reportCode}
          {envelope.standard ? `  ·  ${envelope.standard}` : ""}
          {`  ·  ${envelope.currency} (ISO 4217)`}
        </div>
        {(envelope.periodStart || envelope.periodEnd) && (
          <div className="text-xs text-muted-foreground">
            Period: {envelope.periodStart ?? "—"} → {envelope.periodEnd ?? "—"} (ISO 8601)
          </div>
        )}
        {envelope.filters.length > 0 && (
          <div className="text-xs text-muted-foreground">
            Filters: {envelope.filters.map((f) => `${f.label}=${f.value}`).join("  ·  ")}
          </div>
        )}
        <div className="text-xs text-muted-foreground">
          Generated by {envelope.generatedBy} · {envelope.generatedAt}
        </div>
      </div>

      <ScrollArea className="h-[420px]">
        <Table>
          <TableHeader className="sticky top-0 bg-muted">
            <TableRow>
              {envelope.columns.map((c) => (
                <TableHead
                  key={c.key}
                  className={cn(
                    c.align === "right" && "text-right",
                    c.align === "center" && "text-center",
                  )}
                >
                  {c.label}
                </TableHead>
              ))}
            </TableRow>
          </TableHeader>
          <TableBody>
            {envelope.rows.length === 0 && (
              <TableRow>
                <TableCell
                  colSpan={envelope.columns.length}
                  className="text-center text-muted-foreground py-8"
                >
                  No data for the selected parameters.
                </TableCell>
              </TableRow>
            )}
            {envelope.rows.map((row, i) => (
              <TableRow key={i}>
                {envelope.columns.map((c) => {
                  const align =
                    c.align ??
                    (c.type === "number" || c.type === "currency" || c.type === "integer"
                      ? "right"
                      : "left");
                  return (
                    <TableCell
                      key={c.key}
                      className={cn(
                        align === "right" && "text-right tabular-nums",
                        align === "center" && "text-center",
                      )}
                    >
                      {formatValue(row[c.key], c, envelope.currency)}
                    </TableCell>
                  );
                })}
              </TableRow>
            ))}
            {envelope.totals && envelope.rows.length > 0 && (
              <TableRow className="font-semibold border-t-2">
                {envelope.columns.map((c, idx) => {
                  const v = envelope.totals?.[c.key];
                  const align =
                    c.align ??
                    (c.type === "number" || c.type === "currency" || c.type === "integer"
                      ? "right"
                      : "left");
                  return (
                    <TableCell
                      key={c.key}
                      className={cn(
                        align === "right" && "text-right tabular-nums",
                        align === "center" && "text-center",
                      )}
                    >
                      {v === undefined && idx === 0
                        ? "Total"
                        : v === undefined || v === null
                          ? ""
                          : formatValue(v, c, envelope.currency)}
                    </TableCell>
                  );
                })}
              </TableRow>
            )}
          </TableBody>
        </Table>
      </ScrollArea>

      <div className="border-t px-4 py-2 text-xs text-muted-foreground flex justify-between">
        <span>Lyceum ERP · Confidential — Internal Use</span>
        <span>{envelope.rows.length} rows</span>
      </div>
    </div>
  );
}
