// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Public project URL + anon (publishable) key. These are safe to ship in the
// client bundle by design — RLS is the security boundary, not this key. They are
// used as fallbacks so a production build with missing/empty VITE_* build env
// (e.g. CI without the Docker build-args set) still boots instead of throwing
// "supabaseKey is required" and rendering a blank page. VITE_* env still wins.
const FALLBACK_SUPABASE_URL = 'https://ajsyvuozkgcnnvvefeed.supabase.co';
const FALLBACK_SUPABASE_PUBLISHABLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqc3l2dW96a2djbm52dmVmZWVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNzg1NzYsImV4cCI6MjA3Mzc1NDU3Nn0.FlmuH3bEof12Bjetv-_3hKY13elsE6smhR4ie3imePA';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || FALLBACK_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || FALLBACK_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    // Stable key — keeps the installed PWA signed in across deploys so QR
    // scans opened inside the installed app reuse the existing session.
    storageKey: 'lgh-erp-auth',
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});
